import { useEffect, useState } from 'react';
import { CheckCircle2, Copy, Facebook, Instagram, Link2, RefreshCw, ShieldCheck, Unplug } from 'lucide-react';
import { useLocation, useNavigate } from 'react-router-dom';
import { api, formatDate } from '../lib/api.js';
import StatusBadge from '../components/StatusBadge.jsx';

export default function AccountsPage(){const[status,setStatus]=useState(null);const[pages,setPages]=useState([]);const[selectedPage,setSelectedPage]=useState('');const[error,setError]=useState('');const[message,setMessage]=useState('');const location=useLocation();const navigate=useNavigate();const pending=new URLSearchParams(location.search).get('meta_pending');const oauthError=new URLSearchParams(location.search).get('meta_error');
 async function load(){try{setStatus(await api('/api/meta/status'));setError('')}catch(e){setError(e.message)}}useEffect(()=>{load()},[]);useEffect(()=>{if(oauthError)setError(oauthError);if(pending)api(`/api/meta/pending/${pending}/pages`).then(r=>{setPages(r.pages);setSelectedPage(r.pages[0]?.id||'')}).catch(e=>setError(e.message))},[pending,oauthError]);
 async function select(){try{const result=await api(`/api/meta/pending/${pending}/select`,{method:'POST',body:JSON.stringify({pageId:selectedPage})});setMessage(`Facebook Page “${result.page.name}” 연결을 저장했습니다.${result.instagram?' Instagram도 확인되었습니다.':' 연결된 Instagram 프로페셔널 계정은 없습니다.'}`);setPages([]);navigate('/accounts',{replace:true});await load()}catch(e){setError(e.message)}}
 async function test(){try{await api('/api/meta/test',{method:'POST'});setMessage('Meta 연결 테스트를 통과했습니다.');await load()}catch(e){setError(e.message)}}
 async function disconnect(){if(!window.confirm('Instagram과 Facebook Page 연결 정보를 삭제할까요?'))return;try{await api('/api/meta/disconnect',{method:'POST'});setMessage('Meta 연결을 해제했습니다.');await load()}catch(e){setError(e.message)}}
 function copy(value){navigator.clipboard.writeText(value);setMessage('클립보드에 복사했습니다.')}
 const facebook=status?.connections?.facebook||{};const instagram=status?.connections?.instagram||{};
 return <div className="page-wrap"><header className="page-header"><div><span className="eyebrow">CONNECTIONS</span><h1>계정 연동</h1><p>비밀번호를 받지 않고 Meta 공식 OAuth 승인으로 연결합니다.</p></div><button className="button button-secondary" onClick={load}><RefreshCw size={16}/>상태 확인</button></header>{error?<div className="alert alert-error">{error}</div>:null}{message?<div className="alert alert-success">{message}</div>:null}
 {pages.length?<section className="panel highlight-panel"><div className="panel-heading"><div><span className="eyebrow">PAGE SELECTION</span><h2>관리할 Facebook Page 선택</h2><p>선택한 Page와 연결된 Instagram 프로페셔널 계정을 함께 확인합니다.</p></div></div><div className="page-choice-list">{pages.map(page=><label className={`page-choice ${selectedPage===page.id?'selected':''}`} key={page.id}><input type="radio" name="page" value={page.id} checked={selectedPage===page.id} onChange={()=>setSelectedPage(page.id)}/><div><strong>{page.name}</strong><span>{page.instagram?`Instagram @${page.instagram.username||page.instagram.name||page.instagram.id}`:'연결된 Instagram 프로페셔널 계정 없음'}</span><small>권한 작업: {(page.tasks||[]).join(', ')||'응답 없음'}</small></div>{page.instagram?<CheckCircle2 size={20}/>:null}</label>)}</div><button className="button button-primary" onClick={select} disabled={!selectedPage}>선택한 Page 연결 저장</button></section>:null}
 <section className="account-grid"><article className="account-card"><div className="account-icon"><Instagram size={24}/></div><div className="account-top"><div><span>Instagram</span><h2>{instagram.account_name?`@${instagram.account_name}`:'프로페셔널 계정'}</h2></div><StatusBadge value={instagram.status}/></div><dl className="definition-list"><div><dt>계정 ID</dt><dd>{instagram.instagram_account_id||'—'}</dd></div><div><dt>마지막 확인</dt><dd>{formatDate(instagram.last_checked_at)}</dd></div><div><dt>토큰 만료</dt><dd>{formatDate(instagram.token_expires_at,'응답 없음')}</dd></div></dl></article>
 <article className="account-card"><div className="account-icon"><Facebook size={24}/></div><div className="account-top"><div><span>Facebook</span><h2>{facebook.account_name||'Page'}</h2></div><StatusBadge value={facebook.status}/></div><dl className="definition-list"><div><dt>Page ID</dt><dd>{facebook.page_id||'—'}</dd></div><div><dt>마지막 확인</dt><dd>{formatDate(facebook.last_checked_at)}</dd></div><div><dt>토큰 만료</dt><dd>{formatDate(facebook.token_expires_at,'응답 없음')}</dd></div></dl></article></section>
 <section className="panel"><div className="panel-heading"><div><span className="eyebrow">META OAUTH</span><h2>통합 연결 설정</h2></div><ShieldCheck size={22}/></div>{status&&!status.configured?<div className="alert alert-warning"><strong>서버 설정 필요</strong><span>{status.missing.join(', ')}</span></div>:null}<div className="copy-field"><div><span>OAuth Callback URL</span><code>{status?.callbackUrl||'—'}</code></div><button className="icon-button" onClick={()=>copy(status?.callbackUrl||'')}><Copy size={17}/></button></div><div className="copy-field"><div><span>Graph API 버전</span><code>{status?.graphVersion||'—'}</code></div></div><p className="helper">앱 비밀키와 액세스 토큰은 화면에 표시하거나 브라우저에 저장하지 않습니다.</p><div className="form-actions left">{facebook.status==='connected'?<><button className="button button-secondary" onClick={test}><RefreshCw size={16}/>연결 테스트</button><button className="button button-danger" onClick={disconnect}><Unplug size={16}/>연결 해제</button></>:<button className="button button-primary" disabled={!status?.configured} onClick={()=>{window.location.href='/api/meta/connect'}}><Link2 size={16}/>Meta 계정 연결</button>}</div></section>
 <section className="future-grid"><article><strong>TikTok</strong><span>2차 연동 예정</span><p>공개 직접 게시에는 개발자 앱 심사 요건이 적용될 수 있습니다.</p></article><article><strong>X</strong><span>2차 연동 예정</span><p>API 사용 정책과 사용량 기반 비용을 확인한 뒤 어댑터를 추가합니다.</p></article></section>
 </div>}
