import { useEffect, useState } from 'react';
import { ExternalLink, RefreshCw } from 'lucide-react';
import { api, formatDate } from '../lib/api.js';
import EmptyState from '../components/EmptyState.jsx';

const metrics=[['reach','도달'],['impressions','노출'],['likes','좋아요'],['comments','댓글'],['shares','공유'],['saves','저장'],['clicks','클릭']];
function metric(value){return value==null?'데이터 없음':Number(value).toLocaleString()}
export default function AnalyticsPage(){const[items,setItems]=useState([]);const[error,setError]=useState('');const[syncing,setSyncing]=useState('');async function load(){try{setItems((await api('/api/analytics')).analytics);setError('')}catch(e){setError(e.message)}}useEffect(()=>{load()},[]);async function sync(id){setSyncing(id);setError('');try{await api(`/api/analytics/${id}/sync`,{method:'POST'});await load()}catch(e){setError(e.message)}finally{setSyncing('')}}
 return <div className="page-wrap"><header className="page-header"><div><span className="eyebrow">REAL METRICS</span><h1>성과</h1><p>플랫폼이 실제 반환한 값만 저장합니다. 지원되지 않는 항목은 0으로 만들지 않습니다.</p></div><button className="button button-secondary" onClick={load}><RefreshCw size={16}/>새로고침</button></header>{error?<div className="alert alert-error">{error}</div>:null}{items.length?<div className="analytics-list">{items.map(item=><article className="panel analytics-card" key={item.id}><div className="analytics-heading"><div><span className="eyebrow">{item.platform}</span><h2>{item.campaign_title}</h2><p>{item.caption?.slice(0,140)||'캡션 없음'}</p></div><div className="header-actions">{item.permalink?<a className="button button-ghost" href={item.permalink} target="_blank" rel="noreferrer"><ExternalLink size={15}/>게시물</a>:null}<button className="button button-secondary" onClick={()=>sync(item.id)} disabled={syncing===item.id}><RefreshCw size={15}/>{syncing===item.id?'동기화 중':'동기화'}</button></div></div><div className="metric-grid">{metrics.map(([key,label])=><div key={key}><span>{label}</span><strong>{metric(item[key])}</strong></div>)}</div><footer><span>마지막 동기화: {formatDate(item.captured_at,'아직 동기화하지 않음')}</span>{item.sync_error?<span className="text-warning">일부 지표 오류: {item.sync_error}</span>:null}</footer></article>)}</div>:<EmptyState title="발행된 게시물 성과가 없습니다" description="실제 게시물이 발행된 후 수동 동기화를 실행할 수 있습니다."/>}</div>}
