import { useEffect, useMemo, useState } from 'react';
import { ChevronLeft, ChevronRight, RefreshCw } from 'lucide-react';
import { api, formatDate } from '../lib/api.js';
import StatusBadge from '../components/StatusBadge.jsx';
import EmptyState from '../components/EmptyState.jsx';

function monthRange(date){const start=new Date(date.getFullYear(),date.getMonth(),1);const end=new Date(date.getFullYear(),date.getMonth()+1,1);return{start,end}}
function dateKey(value){const date=new Date(value);if(!Number.isFinite(date.getTime()))return '';const parts=new Intl.DateTimeFormat('en',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date);const map=Object.fromEntries(parts.map(part=>[part.type,part.value]));return `${map.year}-${map.month}-${map.day}`}
export default function CalendarPage(){const[current,setCurrent]=useState(new Date());const[posts,setPosts]=useState([]);const[error,setError]=useState('');const[view,setView]=useState('month');
 async function load(){const{start,end}=monthRange(current);try{setPosts((await api(`/api/calendar?start=${encodeURIComponent(start.toISOString())}&end=${encodeURIComponent(end.toISOString())}`)).posts);setError('')}catch(e){setError(e.message)}}useEffect(()=>{load()},[current]);
 const days=useMemo(()=>{const first=new Date(current.getFullYear(),current.getMonth(),1);const start=new Date(first);start.setDate(first.getDate()-first.getDay());return Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d})},[current]);
 const byDay=useMemo(()=>{const map={};posts.forEach(p=>{const key=dateKey(p.scheduled_at||p.created_at);(map[key]||=[]).push(p)});return map},[posts]);
 return <div className="page-wrap"><header className="page-header"><div><span className="eyebrow">SCHEDULE</span><h1>예약 캘린더</h1><p>모든 시간은 Asia/Seoul로 표시하며 서버에는 UTC로 저장합니다.</p></div><div className="header-actions"><div className="segmented"><button className={view==='month'?'active':''} onClick={()=>setView('month')}>월</button><button className={view==='list'?'active':''} onClick={()=>setView('list')}>목록</button></div><button className="button button-secondary" onClick={load}><RefreshCw size={16}/></button></div></header>{error?<div className="alert alert-error">{error}</div>:null}
 <section className="panel"><div className="calendar-toolbar"><button className="icon-button" onClick={()=>setCurrent(new Date(current.getFullYear(),current.getMonth()-1,1))}><ChevronLeft size={18}/></button><h2>{current.getFullYear()}년 {current.getMonth()+1}월</h2><button className="icon-button" onClick={()=>setCurrent(new Date(current.getFullYear(),current.getMonth()+1,1))}><ChevronRight size={18}/></button><button className="button button-ghost" onClick={()=>setCurrent(new Date())}>오늘</button></div>
 {view==='month'?<div className="calendar-grid"><div className="weekday">일</div><div className="weekday">월</div><div className="weekday">화</div><div className="weekday">수</div><div className="weekday">목</div><div className="weekday">금</div><div className="weekday">토</div>{days.map(day=>{const key=dateKey(day);const inMonth=day.getMonth()===current.getMonth();return <div className={`calendar-day ${!inMonth?'outside':''}`} key={key}><span>{day.getDate()}</span><div>{(byDay[key]||[]).slice(0,4).map(post=><article className={`calendar-event platform-${post.platform}`} key={post.id}><strong>{post.campaign_title}</strong><small>{post.platform} · {new Date(post.scheduled_at||post.created_at).toLocaleTimeString('ko-KR',{timeZone:'Asia/Seoul',hour:'2-digit',minute:'2-digit'})}</small></article>)}</div></div>})}</div>:posts.length?<div className="timeline-list">{posts.map(post=><article key={post.id}><time>{formatDate(post.scheduled_at)}</time><div><strong>{post.campaign_title}</strong><span>{post.product_name||'상품 연결 없음'} · {post.platform} · {post.format}</span>{post.last_error?<small className="text-error">{post.last_error}</small>:null}</div><StatusBadge value={post.publish_state}/></article>)}</div>:<EmptyState title="이달의 게시 일정이 없습니다" description="콘텐츠 작성에서 예약 발행을 등록해 보세요."/>}
 </section></div>}
