import { useEffect, useMemo, useState } from 'react';
import { useLocation } from 'react-router-dom';
import { CalendarClock, Check, ChevronRight, ImagePlus, Instagram, Send, Save, SquareStack } from 'lucide-react';
import { api, formatBytes } from '../lib/api.js';
import StatusBadge from '../components/StatusBadge.jsx';

const platformNames={instagram:'Instagram',facebook:'Facebook Page'};
const formatOptions={instagram:[['image','단일 이미지'],['carousel','캐러셀'],['reel','릴스']],facebook:[['image','단일 이미지'],['carousel','다중 사진'],['video','영상'],['text','텍스트'],['link','링크']]};

function defaultVariant(platform, caption){return {platform,format:'image',caption,altText:'',linkUrl:'',mediaAssetIds:[]}}
function localToIso(value){if(!value)return null;const date=new Date(value);return Number.isFinite(date.getTime())?date.toISOString():null}
function isoToLocalInput(value){if(!value)return '';const date=new Date(value);if(!Number.isFinite(date.getTime()))return '';date.setMinutes(date.getMinutes()-date.getTimezoneOffset());return date.toISOString().slice(0,16)}

export default function ComposePage(){
 const location=useLocation();const campaignFromUrl=new URLSearchParams(location.search).get('campaign');const[editingId,setEditingId]=useState(campaignFromUrl||null);
 const[products,setProducts]=useState([]);const[media,setMedia]=useState([]);const[brand,setBrand]=useState(null);const[connections,setConnections]=useState(null);const[title,setTitle]=useState('');const[productId,setProductId]=useState('');const[master,setMaster]=useState('');const[selected,setSelected]=useState([]);const[channels,setChannels]=useState(['instagram']);const[variants,setVariants]=useState({instagram:defaultVariant('instagram',''),facebook:defaultVariant('facebook','')});const[mode,setMode]=useState('draft');const[schedule,setSchedule]=useState('');const[error,setError]=useState('');const[result,setResult]=useState(null);const[submitting,setSubmitting]=useState(false);
 useEffect(()=>{(async()=>{try{const[p,m,s,c]=await Promise.all([api('/api/products'),api('/api/media'),api('/api/settings'),api('/api/meta/status')]);setProducts(p.products);setMedia(m.media);setBrand(s.brand);setConnections(c);if(campaignFromUrl){const loaded=await api(`/api/campaigns/${campaignFromUrl}`);const campaign=loaded.campaign;setTitle(campaign.title||'');setProductId(campaign.product_id||'');setMaster(campaign.master_caption||'');const mapped={instagram:defaultVariant('instagram',''),facebook:defaultVariant('facebook','')};for(const item of loaded.variants){mapped[item.platform]={platform:item.platform,format:item.format,caption:item.caption||'',altText:item.alt_text||'',linkUrl:item.link_url||'',mediaAssetIds:Array.isArray(item.media_asset_ids)?item.media_asset_ids:[]}}setVariants(mapped);setChannels(loaded.variants.map(item=>item.platform));setSelected([...new Set(loaded.variants.flatMap(item=>Array.isArray(item.media_asset_ids)?item.media_asset_ids:[]))]);setMode(campaign.status==='scheduled'?'schedule':'draft');setSchedule(isoToLocalInput(loaded.variants.find(item=>item.scheduled_at)?.scheduled_at));}}catch(e){setError(e.message)}})()},[campaignFromUrl]);
 const hashtagLine=useMemo(()=>Array.isArray(brand?.default_hashtags)?brand.default_hashtags.join(' '):'', [brand]);
 function generateVariants(){const caption=[master.trim(),hashtagLine].filter(Boolean).join('\n\n');setVariants(v=>({...v,instagram:{...v.instagram,caption,mediaAssetIds:selected},facebook:{...v.facebook,caption,mediaAssetIds:selected}}))}
 function toggleMedia(id){setSelected(value=>value.includes(id)?value.filter(x=>x!==id):value.length<10?[...value,id]:value)}
 function toggleChannel(platform){setChannels(value=>value.includes(platform)?value.filter(x=>x!==platform):[...value,platform])}
 function updateVariant(platform,patch){setVariants(value=>({...value,[platform]:{...value[platform],...patch}}))}
 async function submit(){setError('');setResult(null);if(!channels.length){setError('발행 채널을 하나 이상 선택해 주세요.');return}if(!title.trim()){setError('캠페인 제목을 입력해 주세요.');return}const payloadVariants=channels.map(platform=>{const value=variants[platform];const noMedia=['text','link'].includes(value.format);return {...value,mediaAssetIds:noMedia?[]:selected}});const actionLabel=mode==='publish'?'즉시 발행':mode==='schedule'?'예약 저장':'초안 저장';if(!window.confirm(`${actionLabel}할까요?\n채널: ${channels.map(x=>platformNames[x]).join(', ')}\n미디어: ${selected.length}개${mode==='schedule'?`\n예약: ${schedule}`:''}`))return;setSubmitting(true);try{const payload={title:title.trim(),productId:productId||null,masterCaption:master,mode,scheduledAt:mode==='schedule'?localToIso(schedule):null,variants:payloadVariants};if(!editingId)payload.clientRequestId=crypto.randomUUID();const wasUpdate=Boolean(editingId);const response=await api(editingId?`/api/campaigns/${editingId}`:'/api/campaigns',{method:editingId?'PUT':'POST',body:JSON.stringify(payload)});setEditingId(response.campaignId);setResult({...response,wasUpdate})}catch(e){setError(e.message)}finally{setSubmitting(false)}}
 const connected=(platform)=>connections?.connections?.[platform]?.status==='connected';
 return <div className="page-wrap"><header className="page-header"><div><span className="eyebrow">COMPOSE</span><h1>{editingId?'캠페인 수정':'콘텐츠 작성'}</h1><p>하나의 캠페인에서 채널별 문구와 형식을 각각 검토합니다.</p></div></header>{error?<div className="alert alert-error">{error}</div>:null}{result?<div className="alert alert-success"><strong>저장 결과</strong><span>캠페인 {result.campaignId.slice(0,8)}가 {result.wasUpdate?'저장되었습니다.':'생성되었습니다.'}</span>{result.publishResults?.map(item=><span key={item.id}>{item.id.slice(0,8)} · {item.ok?'발행 완료':`실패: ${item.error}`}</span>)}</div>:null}
 <div className="compose-layout"><div className="compose-main">
  <section className="panel step-panel"><div className="step-title"><span>01</span><div><h2>상품과 캠페인</h2><p>내부에서 찾기 쉬운 제목과 연결할 상품을 선택하세요.</p></div></div><div className="form-grid"><label>캠페인 제목<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="예: 8월 캡슐 목걸이 신상품"/></label><label>상품(선택)<select value={productId} onChange={e=>setProductId(e.target.value)}><option value="">상품 연결 안 함</option>{products.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label></div></section>
  <section className="panel step-panel"><div className="step-title"><span>02</span><div><h2>미디어 선택</h2><p>캐러셀은 2~10장, 단일 이미지와 영상은 1개를 선택하세요.</p></div><strong>{selected.length}/10</strong></div>{media.length?<div className="asset-picker">{media.map(asset=><button type="button" className={`asset-option ${selected.includes(asset.id)?'selected':''}`} key={asset.id} onClick={()=>toggleMedia(asset.id)}><div>{asset.media_type==='image'?<img src={`/api/media/${asset.id}/preview`} alt=""/>:<video src={`/api/media/${asset.id}/preview`} muted preload="metadata"/>}{selected.includes(asset.id)?<span className="asset-check"><Check size={15}/></span>:null}</div><span>{asset.original_name}</span><small>{formatBytes(asset.bytes)}</small></button>)}</div>:<div className="inline-empty"><ImagePlus size={22}/><span>미디어 라이브러리에서 파일을 먼저 업로드하세요.</span></div>}</section>
  <section className="panel step-panel"><div className="step-title"><span>03</span><div><h2>채널과 문구</h2><p>마스터 문구를 바탕으로 채널별 편집본을 만듭니다.</p></div></div><label>마스터 캡션<textarea rows="6" value={master} onChange={e=>setMaster(e.target.value)} placeholder="제품의 핵심과 고객이 느낄 장면을 간결하게 작성"/><small>{master.length.toLocaleString()}자</small></label><div className="inline-actions"><button className="button button-secondary" type="button" onClick={generateVariants}><SquareStack size={16}/>채널별 문구 만들기</button><span className="helper">저장된 기본 해시태그를 붙이는 결정형 템플릿입니다. AI 결과를 가장하지 않습니다.</span></div><div className="channel-toggle-row">{['instagram','facebook'].map(platform=><button type="button" key={platform} className={`channel-toggle ${channels.includes(platform)?'selected':''}`} onClick={()=>toggleChannel(platform)}><Instagram size={18}/><div><strong>{platformNames[platform]}</strong><span>{connected(platform)?'연결됨':'연결 필요'}</span></div><StatusBadge value={connections?.connections?.[platform]?.status}/></button>)}</div>
   {channels.map(platform=><article className="variant-editor" key={platform}><div className="variant-heading"><div><strong>{platformNames[platform]}</strong><span>채널별 최종본</span></div><StatusBadge value={connections?.connections?.[platform]?.status}/></div><div className="form-grid"><label>형식<select value={variants[platform].format} onChange={e=>updateVariant(platform,{format:e.target.value})}>{formatOptions[platform].map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label>{platform==='facebook'&&variants[platform].format==='link'?<label>링크 URL<input type="url" value={variants[platform].linkUrl} onChange={e=>updateVariant(platform,{linkUrl:e.target.value})}/></label>:<label>대체 텍스트<input value={variants[platform].altText} onChange={e=>updateVariant(platform,{altText:e.target.value})} placeholder="시각 정보를 설명"/></label>}<label className="full-span">캡션<textarea rows="7" value={variants[platform].caption} onChange={e=>updateVariant(platform,{caption:e.target.value})}/><small>{variants[platform].caption.length.toLocaleString()}자</small></label></div></article>)}
  </section>
  <section className="panel step-panel"><div className="step-title"><span>04</span><div><h2>저장 또는 발행</h2><p>실제 계정 발행 전 최종 확인 창이 한 번 더 표시됩니다.</p></div></div><div className="mode-grid"><button className={mode==='draft'?'selected':''} onClick={()=>setMode('draft')}><Save size={19}/><strong>초안 저장</strong><span>게시하지 않고 보관</span></button><button className={mode==='schedule'?'selected':''} onClick={()=>setMode('schedule')}><CalendarClock size={19}/><strong>예약 발행</strong><span>KST 기준 일정 저장</span></button><button className={mode==='publish'?'selected':''} onClick={()=>setMode('publish')}><Send size={19}/><strong>지금 발행</strong><span>연결 계정에 즉시 요청</span></button></div>{mode==='schedule'?<label>예약 시간 (Asia/Seoul)<input type="datetime-local" value={schedule} onChange={e=>setSchedule(e.target.value)}/></label>:null}<button className="button button-primary button-wide" onClick={submit} disabled={submitting}>{submitting?'처리 중…':<>최종 확인 <ChevronRight size={17}/></>}</button></section>
 </div><aside className="compose-sidebar"><div className="preview-card"><span className="eyebrow">SUMMARY</span><h3>{title||'캠페인 제목'}</h3><dl className="definition-list"><div><dt>상품</dt><dd>{products.find(p=>p.id===productId)?.name||'연결 안 함'}</dd></div><div><dt>채널</dt><dd>{channels.map(x=>platformNames[x]).join(', ')||'없음'}</dd></div><div><dt>미디어</dt><dd>{selected.length}개</dd></div><div><dt>동작</dt><dd>{mode==='draft'?'초안 저장':mode==='schedule'?'예약 발행':'즉시 발행'}</dd></div></dl><div className="preview-caption">{variants[channels[0]]?.caption||master||'채널별 캡션 미리보기'}</div></div></aside></div>
 </div>}
