import { useEffect, useState } from 'react';
import { ExternalLink, Plus, X } from 'lucide-react';
import { api, formatDate } from '../lib/api.js';
import EmptyState from '../components/EmptyState.jsx';

const empty={name:'',category:'',confirmedMaterial:'',variant:'',price:'',productUrl:'',keyPoints:[],active:true};
export default function ProductsPage(){const[products,setProducts]=useState([]);const[form,setForm]=useState(empty);const[editing,setEditing]=useState(null);const[point,setPoint]=useState('');const[error,setError]=useState('');const[open,setOpen]=useState(false);
 async function load(){try{setProducts((await api('/api/products?includeInactive=true')).products);setError('')}catch(e){setError(e.message)}} useEffect(()=>{load()},[]);
 function edit(item){setEditing(item.id);setForm({name:item.name||'',category:item.category||'',confirmedMaterial:item.confirmed_material||'',variant:item.variant||'',price:item.price||'',productUrl:item.product_url||'',keyPoints:item.key_points||[],active:item.active});setOpen(true)}
 function reset(){setEditing(null);setForm(empty);setPoint('');setOpen(false)}
 async function save(e){e.preventDefault();try{await api(editing?`/api/products/${editing}`:'/api/products',{method:editing?'PUT':'POST',body:JSON.stringify(form)});reset();await load()}catch(err){setError(err.message)}}
 function addPoint(){const value=point.trim();if(value&&!form.keyPoints.includes(value))setForm({...form,keyPoints:[...form.keyPoints,value]});setPoint('')}
 return <div className="page-wrap"><header className="page-header"><div><span className="eyebrow">PRODUCT CONTENT</span><h1>상품</h1><p>확인된 정보만 저장해 콘텐츠 작성 시 재사용합니다.</p></div><button className="button button-primary" onClick={()=>setOpen(true)}><Plus size={17}/>상품 추가</button></header>{error?<div className="alert alert-error">{error}</div>:null}
 {open?<section className="panel"><div className="panel-heading"><h2>{editing?'상품 수정':'새 상품'}</h2><button className="icon-button" onClick={reset}><X size={18}/></button></div><form className="form-grid" onSubmit={save}><label>상품명<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>카테고리<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} placeholder="목걸이, 반지 등"/></label><label>확인된 소재<input value={form.confirmedMaterial} onChange={e=>setForm({...form,confirmedMaterial:e.target.value})} placeholder="근거가 있는 경우에만"/></label><label>색상/옵션<input value={form.variant} onChange={e=>setForm({...form,variant:e.target.value})}/></label><label>가격(선택)<input type="number" min="0" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>상품 URL<input type="url" value={form.productUrl} onChange={e=>setForm({...form,productUrl:e.target.value})}/></label><label className="full-span">핵심 포인트<div className="inline-field"><input value={point} onChange={e=>setPoint(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addPoint()}}}/><button type="button" className="button button-secondary" onClick={addPoint}>추가</button></div><div className="tag-list">{form.keyPoints.map(p=><button type="button" key={p} className="tag" onClick={()=>setForm({...form,keyPoints:form.keyPoints.filter(x=>x!==p)})}>{p} ×</button>)}</div></label><label className="checkbox-field"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>활성 상품</label><div className="form-actions"><button type="button" className="button button-secondary" onClick={reset}>취소</button><button className="button button-primary">저장</button></div></form></section>:null}
 {products.length?<section className="panel table-wrap"><table><thead><tr><th>상품명</th><th>카테고리</th><th>확인된 소재</th><th>옵션</th><th>상태</th><th>수정일</th></tr></thead><tbody>{products.map(p=><tr key={p.id} onClick={()=>edit(p)} className="clickable-row"><td><strong>{p.name}</strong>{p.product_url?<a href={p.product_url} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()}><ExternalLink size={13}/></a>:null}</td><td>{p.category||'—'}</td><td>{p.confirmed_material||'미확인'}</td><td>{p.variant||'—'}</td><td>{p.active?'활성':'비활성'}</td><td>{formatDate(p.updated_at)}</td></tr>)}</tbody></table></section>:<EmptyState title="등록된 상품이 없습니다" description="콘텐츠에 반복 사용할 상품 정보를 먼저 추가하세요."/>}</div>}
