import { createHash } from 'node:crypto';
import { exactKeys, reportingError, scopedCustomer, assertReportingScope, validDate, utcTimestamp } from '../reporting/contracts.js';
export const CHANNELS = Object.freeze(['haar_naver_smartstore','haar_own_mall']);
export const CAPABILITIES = Object.freeze(['productState','orderLines','adjustments','settlements']);
export const fail = (code='SEARCHAD_PRODUCT_INPUT',status=400) => reportingError(code,status);
export const hash = value => createHash('sha256').update(JSON.stringify(value)).digest('hex');
export function uuid(value) { if(typeof value!=='string'||!/^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i.test(value))throw fail();return value.toLowerCase(); }
export function exact(input,keys){exactKeys(input,keys,'SEARCHAD_PRODUCT_INPUT');}
export function access(customerId,context,role='reader'){scopedCustomer(customerId);assertReportingScope(customerId,context,{readOnly:role==='reader'});if(role==='admin'&&context.principal.role!=='admin')throw fail('SEARCHAD_PRODUCT_ROLE_FORBIDDEN',403);}
export function range(input){if(!validDate(input.since)||!validDate(input.until)||input.since>input.until||Date.parse(input.until)-Date.parse(input.since)>30*86400000)throw fail();return {since:input.since,until:input.until};}
export function effective(input,clock){const validFrom=input.validFrom===undefined?new Date(clock()).toISOString():utcTimestamp(input.validFrom);const validTo=input.validTo==null?null:utcTimestamp(input.validTo);if(validTo&&validTo<=validFrom)throw fail();return {validFrom,validTo};}
export function money(value){if(typeof value!=='number'&&typeof value!=='string'||typeof value==='number'&&!Number.isSafeInteger(value))return null;const text=String(value);return /^-?(0|[1-9]\d{0,14})(\.\d{1,4})?$/.test(text)&&Number.isFinite(Number(text))?text:null;}
export const count=value=>{const result=money(value);return result!==null&&/^(0|[1-9]\d*)$/.test(result)?result:null;};
export const enumValue=(value,values)=>values.includes(value)?value:null;
export function dateValue(value){return validDate(value)?value:null;}
export function timeValue(value){if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}T/.test(value)||!Number.isFinite(Date.parse(value)))return null;return new Date(value).toISOString();}
export function validateMapping(input){exact(input,['customerId','haarProductId','channelProductKey','entityType','entityId','method','allocation','validFrom','validTo']);scopedCustomer(input.customerId);uuid(input.haarProductId);if(typeof input.channelProductKey!=='string'||! /^(haar_naver_smartstore|haar_own_mall):[A-Za-z0-9_-]{1,100}$/.test(input.channelProductKey)||!['campaign','adgroup','keyword','creative'].includes(input.entityType)||! /^[A-Za-z0-9_-]{1,200}$/.test(input.entityId)||input.method!=='manual')throw fail();return {...input,liveVerified:false,autoEligible:false};}
export function normalizeAllocation(value,products){const ids=[...new Set(products)].sort();if(value==null){if(ids.length>1)throw fail('SEARCHAD_MAPPING_ALLOCATION_REQUIRED');return {weights:ids.map(haarProductId=>({haarProductId,weight:'1'})),basis:'manual',verified:false};}exact(value,['weights']);if(!Array.isArray(value.weights)||value.weights.length!==ids.length)throw fail('SEARCHAD_MAPPING_ALLOCATION_REQUIRED');let sum=0;const weights=value.weights.map(row=>{exact(row,['haarProductId','weight']);const id=uuid(row.haarProductId);if(typeof row.weight!=='string'||! /^(0(?:\.\d{1,4})?|1(?:\.0{1,4})?)$/.test(row.weight)||Number(row.weight)<=0)throw fail();sum+=Math.round(Number(row.weight)*10000);return {haarProductId:id,weight:row.weight};}).sort((a,b)=>a.haarProductId.localeCompare(b.haarProductId));if(sum!==10000||JSON.stringify(weights.map(r=>r.haarProductId))!==JSON.stringify(ids))throw fail('SEARCHAD_MAPPING_ALLOCATION_REQUIRED');return {weights,basis:'manual',verified:false};}
const numeric=['stockQuantity','quantity','remainingQuantity','paidAmountKrw','netRevenueKrw','amountKrw','paySettleAmountKrw','totalPayCommissionAmountKrw','freeInstallmentCommissionAmountKrw','sellingInterlockCommissionAmountKrw','benefitSettleAmountKrw','settleExpectAmountKrw'];
const states=['WAIT','SALE','OUTOFSTOCK','UNADMISSION','REJECTION','SUSPENSION','CLOSE','PROHIBITION','DELETE','STOPPED','DISPLAY_ONLY','PAYMENT_WAITING','PAYED','DELIVERING','DELIVERED','PURCHASE_DECIDED','EXCHANGED','CANCELED','RETURNED','CANCELED_BY_NOPAYMENT','CANCEL','RETURN','EXCHANGE','ADMIN_CANCEL','CANCEL_DONE','RETURN_DONE','EXCHANGE_DONE','ADMIN_CANCEL_DONE','NORMAL_SETTLE_ORIGINAL','NORMAL_SETTLE_AFTER_CANCEL','NORMAL_SETTLE_BEFORE_CANCEL','QUICK_SETTLE_ORIGINAL','QUICK_SETTLE_CANCEL','QUANTITY_CANCEL_DEDUCTION','QUANTITY_CANCEL_RESTORE'];
/** Positive projection at the persistence boundary. No raw IDs, free text, payloads or URLs. */
export function safeRows(rows){return rows.map(row=>{if(!/^[a-f0-9]{64}$/.test(row.sourceReference||''))throw fail('SEARCHAD_COMMERCE_RESPONSE_INVALID',502);const out={sourceReference:row.sourceReference};for(const key of numeric)if(Object.hasOwn(row,key))out[key]=money(row[key]);for(const key of ['saleState','orderState','claimType','claimState','settleType'])if(Object.hasOwn(row,key))out[key]=enumValue(row[key],states);for(const key of ['settleBasisDate','settleCompleteDate','payDate'])if(Object.hasOwn(row,key))out[key]=dateValue(row[key]);for(const key of ['occurredAt'])if(Object.hasOwn(row,key))out[key]=timeValue(row[key]);for(const key of ['alreadyIncludedInNetRevenue'])if(Object.hasOwn(row,key))out[key]=typeof row[key]==='boolean'?row[key]:null;for(const key of ['orderReference','variantReference'])if(Object.hasOwn(row,key))out[key]=/^[a-f0-9]{64}$/.test(row[key]||'')?row[key]:null;return out;});}
export function deduplicate(rows){const map=new Map();let conflict=false;for(const row of safeRows(rows)){const prior=map.get(row.sourceReference);if(prior&&JSON.stringify(prior)!==JSON.stringify(row))conflict=true;map.set(row.sourceReference,row);}return {rows:[...map.values()],conflict};}
