import { CHANNELS, exact, access, effective, uuid, hash, money, validateMapping, fail } from './contracts.js';
export class ProductMappingService {
  constructor({repository,providers,identityResolver,clock=Date.now}){Object.assign(this,{repository,providers,identityResolver,clock});}
  identity(customerId){return hash(this.identityResolver(customerId));}
  async bindCustomerChannel(input,context){exact(input,['customerId','channelId']);access(input.customerId,context,'admin');if(!CHANNELS.includes(input.channelId))throw fail();const provider=this.providers.get(input.channelId);if(!provider)throw fail('SEARCHAD_COMMERCE_PROVIDER_UNAVAILABLE',503);return this.repository.appendBinding({...input,identityHash:this.identity(input.customerId),sourceIdentity:provider.sourceIdentity,actorHash:hash(context.principal.principalId)});}
  async createRevision(input,context){validateMapping(input);access(input.customerId,context,'admin');const channelId=input.channelProductKey.split(':')[0];const provider=this.providers.get(channelId);if(!provider)throw fail('SEARCHAD_COMMERCE_PROVIDER_UNAVAILABLE',503);return this.repository.appendMapping({...input,...effective(input,this.clock),identityHash:this.identity(input.customerId),sourceIdentity:provider.sourceIdentity,actorHash:hash(context.principal.principalId)});}
  async resolve({customerId,haarProductId,at}){return this.repository.resolve({customerId,haarProductId,at,identityHash:this.identity(customerId)});}
  async appendCost(input,context){exact(input,['customerId','haarProductId','haarVariantId','component','amountKrw','sourceReference','reason','validFrom','validTo']);access(input.customerId,context,'admin');uuid(input.haarProductId);if(input.haarVariantId!=null)uuid(input.haarVariantId);if(!['cogs','fees','shipping','seller_discount','return_provision'].includes(input.component)||money(input.amountKrw)===null||Number(input.amountKrw)<0||typeof input.sourceReference!=='string'||input.sourceReference.length<1||input.sourceReference.length>500||typeof input.reason!=='string'||input.reason.length<1||input.reason.length>500)throw fail();const identityHash=this.identity(input.customerId);const mappings=await this.resolve({...input,at:new Date(this.clock()).toISOString()});let authorized=false;for(const m of mappings){const provider=this.providers.get(m.channelId);const binding=provider&&await this.repository.getVerifiedChannelBinding({customerId:input.customerId,channelId:m.channelId,identityHash,sourceIdentity:provider.sourceIdentity});if(binding&&binding.bindingId===m.bindingId&&binding.identityHash===m.identityHash&&binding.identityHash===identityHash&&binding.sourceIdentity===provider.sourceIdentity)authorized=true;}if(!authorized)throw fail('SEARCHAD_CUSTOMER_CHANNEL_BINDING_REQUIRED',409);return this.repository.appendCostInput({customerId:input.customerId,haarProductId:input.haarProductId,haarVariantId:input.haarVariantId??null,component:input.component,amountKrw:money(input.amountKrw),sourceHash:hash(input.sourceReference),reasonHash:hash(input.reason),actorHash:hash(context.principal.principalId),...effective(input,this.clock)});}
}
