import test from 'node:test';
import assert from 'node:assert/strict';
import { postgresCompletionFixture, completionReaderKey, completionOperatorKey } from './helpers/postgres-searchad-completion-fixture.js';
const enabled=Boolean(process.env.TEST_DATABASE_URL);
test('commerce_provider_is_wired_in_bootstrap', {skip:!enabled},async t=>{const f=await postgresCompletionFixture(t);const {app}=await f.start();assert.ok(app.searchAdCompletionRuntime.productEvidenceService);assert.ok(app.searchAdCompletionRuntime.productMappingService);assert.ok(app.searchAdCompletionRuntime.commerceProviders.get('haar_naver_smartstore'));assert.equal(app.searchAdCompletionRuntime.commerceProviders.has('cafe24'),false);});

import fs from 'node:fs';
import { randomUUID } from 'node:crypto';
import { listMigrationFiles,runPostgresMigrations } from '../src/infrastructure/postgres/migrator.js';
const adminKey='product-evidence-admin-'.repeat(4);
const env={ATELIER_COMMERCE_ALLOW_UNVERIFIED_OPERATIONS:'true',ATELIER_SEARCHAD_ADMIN_API_KEY:adminKey,ATELIER_SEARCHAD_ADMIN_CUSTOMERS:'1001',ATELIER_SEARCHAD_ADMIN_PRINCIPAL_ID:'product-admin'};
const fixture=name=>JSON.parse(fs.readFileSync(`test/fixtures/searchad-profitability/${name}.json`));
async function setup(t){const f=await postgresCompletionFixture(t);const server=await f.start({appEnv:env});const id=randomUUID(),cp=randomUUID();await f.pool.query("INSERT INTO haar_products(haar_product_id,product_name) VALUES($1,'canonical')",[id]);await f.pool.query("INSERT INTO channel_products(channel_product_id,channel_id,haar_product_id,channel_product_no,remote_product_id,channel_product_key,product_name) VALUES($1,'haar_naver_smartstore',$2,'123','123','haar_naver_smartstore:123','canonical')",[cp,id]);const calls=[];server.app.client.tokenProvider.cached={accessToken:'synthetic-commerce-token',issuedAt:Date.now(),expiresIn:3600};server.app.client.fetchImpl=async(url,init)=>{assert.equal(init.method,'GET');const target=new URL(url);assert.equal(target.origin,'https://api.commerce.naver.com');assert.equal(init.headers.Authorization,'Bearer synthetic-commerce-token');const file={'/external/v2/products/channel-products/123':'naver-product','/external/v1/pay-order/seller/product-orders':'naver-orders','/external/v1/pay-settle/settle/case':'naver-settlements'}[target.pathname];assert.ok(file,'only exact read endpoints');calls.push({path:target.pathname,query:Object.fromEntries(target.searchParams)});return new Response(JSON.stringify(fixture(file)),{headers:{'content-type':'application/json'}});};return {...f,...server,id,cp,commerceCalls:calls};}
const bind=f=>f.call(adminKey,'POST','/api/v1/searchad/customer-channel-bindings',{customerId:'1001',channelId:'haar_naver_smartstore'});
const mapping=f=>({customerId:'1001',haarProductId:f.id,channelProductKey:'haar_naver_smartstore:123',entityType:'campaign',entityId:'cmp-1',method:'manual',validFrom:'2026-10-01T00:00:00Z'});
const collect=f=>({customerId:'1001',haarProductId:f.id,since:'2026-10-01',until:'2026-10-01'});
test('customer_channel_binding_required',{skip:!enabled},async t=>{const f=await setup(t);const result=await f.call(adminKey,'POST','/api/v1/searchad/product-mappings',mapping(f));assert.equal(result.status,409);assert.equal(f.commerceCalls.length,0);assert.equal((await bind(f)).status,200);assert.equal((await f.call(adminKey,'POST','/api/v1/searchad/product-mappings',mapping(f))).status,200);for(const extra of [{customerId:'9999'},{accountId:'other'},{trusted:true},{liveVerified:true},{operationId:'post_v1_pay_order_seller_product_orders_confirm'},{path:'/evil'}]){const r=await f.call(completionOperatorKey,'POST','/api/v1/searchad/product-evidence/collect',{...collect(f),...extra});assert.ok([400,403].includes(r.status));}assert.equal(f.commerceCalls.length,0);});
test('buyer_pii_never_persists; missing_settlement_is_partial_not_zero; real configured provider delegation and restart',{skip:!enabled},async t=>{const f=await setup(t);await bind(f);assert.equal((await f.call(adminKey,'POST','/api/v1/searchad/product-mappings',mapping(f))).status,200);const result=await f.call(completionOperatorKey,'POST','/api/v1/searchad/product-evidence/collect',collect(f));assert.equal(result.status,200);assert.equal(result.body.quality,'partial');assert.equal(result.body.settlementAmountKrw,null);assert.equal(result.body.contributionKrw,null);assert.equal(result.body.autoEligible,false);assert.equal(f.commerceCalls.length,4);assert.equal(result.body.observations.find(o=>o.capability==='orderLines').rows.length,1);assert.equal(result.body.observations.find(o=>o.capability==='adjustments').rows.length,1);const before=(await f.pool.query('SELECT count(*)::int AS n FROM searchad_commerce_observations')).rows[0].n;assert.equal(before,4);await f.call(completionOperatorKey,'POST','/api/v1/searchad/product-evidence/collect',collect(f));assert.equal((await f.pool.query('SELECT count(*)::int AS n FROM searchad_commerce_observations')).rows[0].n,before);const persisted=JSON.stringify((await f.pool.query('SELECT * FROM searchad_commerce_observations')).rows);for(const sentinel of ['PRIVATE_BUYER','01012345678','https://signed','synthetic-commerce-token','shippingAddress','purchaserName','order-1','claim-1'])assert.equal(persisted.includes(sentinel),false,sentinel);await assert.rejects(()=>f.pool.query('UPDATE searchad_commerce_observations SET complete=true'));await assert.rejects(()=>f.pool.query('DELETE FROM product_ad_mappings WHERE source_product_id IS NULL'));await f.api.close();const restarted=await f.start({appEnv:env});const summary=await restarted.call(completionReaderKey,'GET',`/api/v1/searchad/profitability/products/${f.id}?customerId=1001&since=2026-10-01&until=2026-10-01`);assert.equal(summary.status,200);assert.equal(summary.body.observations.length,4);assert.equal(summary.body.autoEligible,false);assert.equal((await restarted.call(completionReaderKey,'POST','/api/v1/searchad/product-evidence/collect',collect(f))).status,403);});
test('manual costs are effective revisions, hashed provenance and never live authority',{skip:!enabled},async t=>{const f=await setup(t);await bind(f);await f.call(adminKey,'POST','/api/v1/searchad/product-mappings',mapping(f));const cost={customerId:'1001',haarProductId:f.id,component:'cogs',amountKrw:'1000',sourceReference:'PRIVATE_BUYER source',reason:'PRIVATE_BUYER reason',validFrom:'2026-10-01T00:00:00Z'};assert.equal((await f.call(adminKey,'POST','/api/v1/searchad/product-costs',{...cost,trusted:true})).status,400);assert.equal((await f.call(adminKey,'POST','/api/v1/searchad/product-costs',cost)).status,200);const rows=(await f.pool.query('SELECT * FROM searchad_product_cost_inputs')).rows;assert.equal(rows[0].provenance,'manual_estimate');assert.equal(JSON.stringify(rows).includes('PRIVATE_BUYER'),false);await assert.rejects(()=>f.pool.query('UPDATE searchad_product_cost_inputs SET amount_krw=0'));});
test('same_supplier_sku_different_sources_do_not_merge',{skip:!enabled},async t=>{const f=await setup(t);await bind(f);await f.call(adminKey,'POST','/api/v1/searchad/product-mappings',mapping(f));for(const [source,cost] of [['supplier-a',100],['supplier-b',900]]){await f.pool.query("INSERT INTO catalog_sources(source_id,source_name,source_type,provider_type) VALUES($1,$1,'supplier','manual_upload')",[source]);await f.pool.query("INSERT INTO source_products(source_id,source_product_id,source_product_name) VALUES($1,'SKU-SAME','source product')",[source]);await f.pool.query("INSERT INTO haar_product_source_links(haar_product_id,source_id,source_product_id,valid_from) VALUES($1,$2,'SKU-SAME','2026-09-01')",[f.id,source]);await f.pool.query("INSERT INTO supplier_cost_history(source_id,source_product_id,supply_cost,effective_from) VALUES($1,'SKU-SAME',$2,'2026-10-01')",[source,cost]);}await f.pool.query("INSERT INTO supplier_cost_history(source_id,source_product_id,supply_cost,effective_from) VALUES('supplier-a','SKU-SAME',200,'2026-10-02')");const result=await f.call(completionReaderKey,'GET',`/api/v1/searchad/profitability/products/${f.id}?customerId=1001&since=2026-10-01&until=2026-10-01`);assert.equal(result.status,200);assert.equal(result.body.sourceCosts.length,2);assert.notEqual(result.body.sourceCosts[0].sourceReference,result.body.sourceCosts[1].sourceReference);assert.deepEqual(result.body.sourceCosts.map(c=>Number(c.amountKrw)).sort((a,b)=>a-b),[100,900]);});
test('exact 0015 immediate repeat and prior migration checksums',{skip:!enabled},async t=>{const f=await postgresCompletionFixture(t);const files=listMigrationFiles('migrations/postgres');assert.equal(files.length,15);const previous=fixture('prior-migration-checksums');assert.deepEqual(Object.fromEntries(files.slice(0,14).map(x=>[x.fileName,x.checksum])),previous.sha256);assert.equal(files.at(-1).fileName,'0015_searchad_profitability.sql');assert.deepEqual(await runPostgresMigrations({pool:f.pool,migrationsDir:'migrations/postgres',logger:{info(){}}}),{applied:[],currentVersion:'0015'});const applied=(await f.pool.query('SELECT version,checksum FROM schema_migrations ORDER BY version')).rows;assert.deepEqual(applied,files.map(({version,checksum})=>({version,checksum})));});
test('expired mapping and cost revisions must not resurrect older authority',{skip:!enabled},async t=>{const f=await setup(t);await bind(f);await f.call(adminKey,'POST','/api/v1/searchad/product-mappings',mapping(f));const service=f.app.searchAdCompletionRuntime.productMappingService;const ctx={principal:{principalId:'test-admin',role:'admin',customerIds:['1001']},requestId:'expiry-test'};await service.createRevision({...mapping(f),validFrom:'2026-10-02T00:00:00Z',validTo:'2026-10-03T00:00:00Z'},ctx);const result=await f.call(completionReaderKey,'GET',`/api/v1/searchad/profitability/products/${f.id}?customerId=1001&since=2026-10-01&until=2026-10-01`);assert.equal(result.status,409,'latest expired revision is a tombstone, not permission to resurrect older mapping');});
test('configured Cafe24 product and variants use real app client with fixed own-mall account',{skip:!enabled},async t=>{const f=await postgresCompletionFixture(t);const server=await f.start({appEnv:{...env,CAFE24_MALL_ID:'fixturemall',CAFE24_CLIENT_ID:'fixture-cafe-app',CAFE24_CLIENT_SECRET:'fixture-cafe-secret',CAFE24_ACCESS_TOKEN:'fixture-cafe-access',CAFE24_ACCESS_TOKEN_EXPIRES_AT:'2030-01-01T00:00:00Z',CAFE24_TOKEN_STORE_PATH:`/tmp/nonexistent-cafe24-${randomUUID()}.json`}});const provider=server.app.searchAdCompletionRuntime.commerceProviders.get('haar_own_mall');assert.ok(provider);const calls=[];provider.client.fetchImpl=async(url,init)=>{assert.equal(init.method,'GET');assert.equal(new URL(url).origin,'https://fixturemall.cafe24api.com');assert.equal(init.headers.get('Authorization'),'Bearer fixture-cafe-access');calls.push(new URL(url).pathname);return new Response(JSON.stringify(fixture(new URL(url).pathname.endsWith('variants')?'cafe24-variants':'cafe24-product')),{headers:{'content-type':'application/json'}});};const id=randomUUID();await f.pool.query("INSERT INTO haar_products(haar_product_id,product_name) VALUES($1,'own mall')",[id]);await f.pool.query("INSERT INTO channel_products(channel_id,haar_product_id,channel_product_no,remote_product_id,channel_product_key,product_name) VALUES('haar_own_mall',$1,'123','123','haar_own_mall:123','own mall')",[id]);assert.equal((await server.call(adminKey,'POST','/api/v1/searchad/customer-channel-bindings',{customerId:'1001',channelId:'haar_own_mall'})).status,200);assert.equal((await server.call(adminKey,'POST','/api/v1/searchad/product-mappings',{...mapping({id}),channelProductKey:'haar_own_mall:123'})).status,200);const response=await server.call(completionOperatorKey,'POST','/api/v1/searchad/product-evidence/collect',collect({id}));assert.equal(response.status,200);assert.equal(response.body.quality,'partial');assert.ok(response.body.missingReasons.includes('CAFE24_SETTLEMENT_CAPABILITY_UNVERIFIED'));assert.equal(response.body.settlementAmountKrw,null);assert.deepEqual(calls,['/api/v2/admin/products/123','/api/v2/admin/products/123/variants']);assert.equal((await f.pool.query("SELECT count(*)::int AS n FROM sales_channels WHERE channel_id IN ('haar_own_mall','cafe24')")).rows[0].n,1);});
test('shared mapping requires exact weights, binding identity rotation fails closed and scope cannot cross canonical products',{skip:!enabled},async t=>{const f=await setup(t);await bind(f);await f.call(adminKey,'POST','/api/v1/searchad/product-mappings',mapping(f));const other=randomUUID();await f.pool.query("INSERT INTO haar_products(haar_product_id,product_name) VALUES($1,'other')",[other]);await f.pool.query("INSERT INTO channel_products(channel_id,haar_product_id,channel_product_no,remote_product_id,channel_product_key,product_name) VALUES('haar_naver_smartstore',$1,'456','456','haar_naver_smartstore:456','other')",[other]);assert.equal((await f.call(adminKey,'POST','/api/v1/searchad/product-mappings',{...mapping(f),haarProductId:other})).status,404);const input={...mapping(f),haarProductId:other,channelProductKey:'haar_naver_smartstore:456'};assert.equal((await f.call(adminKey,'POST','/api/v1/searchad/product-mappings',input)).status,400);assert.equal((await f.call(adminKey,'POST','/api/v1/searchad/product-mappings',{...input,allocation:{weights:[{haarProductId:f.id,weight:'0.6'},{haarProductId:other,weight:'0.4'}]}})).status,200);f.app.searchAdCompletionRuntime.commerceProviders.get('haar_naver_smartstore').sourceIdentity='f'.repeat(64);assert.equal((await f.call(completionOperatorKey,'POST','/api/v1/searchad/product-evidence/collect',collect(f))).status,409);assert.equal(f.commerceCalls.length,0);});
test('default Commerce gate remains OFF for unverified operations and errors never become zero evidence',{skip:!enabled},async t=>{const f=await setup(t);await bind(f);await f.call(adminKey,'POST','/api/v1/searchad/product-mappings',mapping(f));f.app.commerceGateway.config.allowUnverifiedOperations=false;const result=await f.call(completionOperatorKey,'POST','/api/v1/searchad/product-evidence/collect',collect(f));assert.equal(result.status,200);assert.equal(result.body.quality,'unknown');assert.equal(result.body.contributionKrw,null);assert.equal(result.body.settlementAmountKrw,null);assert.equal(f.commerceCalls.length,0);assert.ok(result.body.missingReasons.includes('PROVIDER_READ_UNAVAILABLE'));});
test('headless disposal drains a pending product collection and rejects subsequent work',{skip:!enabled},async t=>{const f=await setup(t);await bind(f);await f.call(adminKey,'POST','/api/v1/searchad/product-mappings',mapping(f));let release,entered;const block=new Promise(r=>release=r),waiting=new Promise(r=>entered=r);const previous=f.app.client.fetchImpl;f.app.client.fetchImpl=async(...args)=>{entered();await block;return previous(...args);};const ctx={principal:{principalId:'op',role:'operator',customerIds:['1001']},requestId:'drain-test'};const pending=f.app.searchAdCompletionRuntime.productEvidenceService.collect(collect(f),ctx);await waiting;let closed=false;const close=f.app.close().then(()=>closed=true);await new Promise(resolve=>setImmediate(resolve));assert.equal(closed,false);release();await pending;await close;assert.equal(closed,true);await assert.rejects(()=>f.app.searchAdCompletionRuntime.productEvidenceService.collect(collect(f),ctx),{code:'SEARCHAD_REPORTING_NOT_READY'});});

const manualCost=f=>({customerId:'1001',haarProductId:f.id,component:'cogs',amountKrw:'1000',sourceReference:'fixture cost',reason:'fixture estimate',validFrom:'2026-10-02T00:00:00Z'});
test('fix1 T8-I1 provider rebind requires a new product mapping before reads or evidence selection',{skip:!enabled},async t=>{
  const f=await setup(t);const originalBinding=await bind(f);
  assert.equal((await f.call(adminKey,'POST','/api/v1/searchad/product-mappings',mapping(f))).status,200);
  assert.equal((await f.call(completionOperatorKey,'POST','/api/v1/searchad/product-evidence/collect',collect(f))).status,200);
  const runtime=f.app.searchAdCompletionRuntime;
  runtime.commerceProviders.get('haar_naver_smartstore').sourceIdentity='f'.repeat(64);
  const currentBinding=await bind(f);assert.equal(currentBinding.status,200);assert.notEqual(currentBinding.body.bindingId,originalBinding.body.bindingId);
  f.commerceCalls.length=0;let appendAttempts=0;
  const append=runtime.productRepository.appendCommerceObservation.bind(runtime.productRepository);
  runtime.productRepository.appendCommerceObservation=async input=>{appendAttempts++;return append(input);};
  const denied=await f.call(completionOperatorKey,'POST','/api/v1/searchad/product-evidence/collect',collect(f));
  assert.equal(denied.status,409,'rebind must not reinterpret the old mapping under a different provider account');
  assert.equal(f.commerceCalls.length,0);assert.equal(appendAttempts,0);
  assert.equal((await f.pool.query('SELECT count(*)::int AS n FROM searchad_commerce_observations')).rows[0].n,4);
  assert.equal((await f.call(completionReaderKey,'GET',`/api/v1/searchad/profitability/products/${f.id}?customerId=1001&since=2026-10-01&until=2026-10-01`)).status,409);
  const remap=await f.call(adminKey,'POST','/api/v1/searchad/product-mappings',{...mapping(f),validFrom:'2026-10-02T00:00:00Z'});
  assert.equal(remap.status,200);assert.equal(remap.body.bindingId,currentBinding.body.bindingId);
  const before=await f.call(completionReaderKey,'GET',`/api/v1/searchad/profitability/products/${f.id}?customerId=1001&since=2026-10-01&until=2026-10-01`);
  assert.equal(before.status,200);assert.deepEqual(before.body.observations,[],'old account evidence remains unusable after explicit remapping');
  const accepted=await f.call(completionOperatorKey,'POST','/api/v1/searchad/product-evidence/collect',collect(f));
  assert.equal(accepted.status,200);assert.equal(f.commerceCalls.length,4);assert.equal(appendAttempts,4);assert.equal(accepted.body.observations.length,4);
  const bindings=(await f.pool.query('SELECT binding_id,count(*)::int AS n FROM searchad_commerce_observations GROUP BY binding_id')).rows;
  assert.deepEqual(bindings.map(row=>[row.binding_id,row.n]).sort(),[[originalBinding.body.bindingId,4],[currentBinding.body.bindingId,4]].sort());
  assert.equal((await f.pool.query('SELECT count(DISTINCT observed_at)::int AS n FROM searchad_commerce_observations')).rows[0].n,1,'old and new generations deliberately share a collection clock');
  const currentIds=(await f.pool.query('SELECT observation_id FROM searchad_commerce_observations WHERE binding_id=$1',[currentBinding.body.bindingId])).rows.map(row=>row.observation_id).sort();
  assert.deepEqual(accepted.body.observations.map(row=>row.observationId).sort(),currentIds,'only current-binding observations survive latest-generation selection');
});
test('fix1 T8-I1 provider rebind cannot authorize costs through an older mapping',{skip:!enabled},async t=>{
  const f=await setup(t);await bind(f);await f.call(adminKey,'POST','/api/v1/searchad/product-mappings',mapping(f));
  f.app.searchAdCompletionRuntime.commerceProviders.get('haar_naver_smartstore').sourceIdentity='f'.repeat(64);await bind(f);
  assert.equal((await f.call(adminKey,'POST','/api/v1/searchad/product-costs',manualCost(f))).status,409);
  assert.equal((await f.pool.query('SELECT count(*)::int AS n FROM searchad_product_cost_inputs')).rows[0].n,0);assert.equal(f.commerceCalls.length,0);
  assert.equal((await f.call(adminKey,'POST','/api/v1/searchad/product-mappings',{...mapping(f),validFrom:'2026-10-02T00:00:00Z'})).status,200);
  assert.equal((await f.call(adminKey,'POST','/api/v1/searchad/product-costs',manualCost(f))).status,200);
});
async function observationScope(t){
  const f=await setup(t);await bind(f);
  const binding=(await f.pool.query('SELECT * FROM searchad_customer_channel_bindings')).rows[0];
  const other=randomUUID(),otherChannel=randomUUID();
  await f.pool.query("INSERT INTO searchad_customer_accounts(customer_id) VALUES('2002')");
  await f.pool.query("INSERT INTO haar_products(haar_product_id,product_name) VALUES($1,'other canonical')",[other]);
  await f.pool.query("INSERT INTO channel_products(channel_product_id,channel_id,haar_product_id,channel_product_no,remote_product_id,channel_product_key,product_name) VALUES($1,'haar_own_mall',$2,'123','123','haar_own_mall:123','other channel')",[otherChannel,f.id]);
  return {...f,other,otherChannel,observation:{customerId:'1001',haarProductId:f.id,channelProductId:f.cp,bindingId:binding.binding_id,identityHash:binding.identity_hash,sourceIdentity:binding.source_identity,capability:'productState',since:'2026-10-01',until:'2026-10-01',rows:[],complete:false,missingReasons:['PRODUCT_STATE_MISSING'],observedAt:'2026-10-02T00:00:00Z'}};
}
const rawObservation=(pool,o)=>pool.query(`INSERT INTO searchad_commerce_observations(customer_id,haar_product_id,channel_product_id,binding_id,capability,since,until,identity_hash,source_identity,source_hash,rows_json,complete,missing_reasons,observed_at) VALUES($1,$2,$3,$4,'productState','2026-10-01','2026-10-01',$5,$6,$7,'[]',false,'["PRODUCT_STATE_MISSING"]','2026-10-02T00:00:00Z') RETURNING observation_id`,[o.customerId,o.haarProductId,o.channelProductId,o.bindingId,o.identityHash,o.sourceIdentity,'a'.repeat(64)]);
for(const [name,override] of [
  ['foreign Customer binding',f=>({customerId:'2002'})],
  ['other HAAR product',f=>({haarProductId:f.other})],
  ['other sales channel',f=>({channelProductId:f.otherChannel})],
  ['different SearchAd identity',()=>({identityHash:'b'.repeat(64)})],
  ['different provider source identity',()=>({sourceIdentity:'c'.repeat(64)})]
])test(`fix1 T8-I2 raw observation insert rejects ${name}`,{skip:!enabled},async t=>{
  const f=await observationScope(t);const invalid={...f.observation,...override(f)};
  await assert.rejects(()=>rawObservation(f.pool,invalid),/commerce observation scope mismatch/);
  assert.equal(await f.app.searchAdCompletionRuntime.productRepository.appendCommerceObservation(invalid),null,'repository guard also denies the mismatched tuple');
  assert.equal((await f.pool.query('SELECT count(*)::int AS n FROM searchad_commerce_observations')).rows[0].n,0);
});
test('fix1 T8-I2 valid raw observation insert is accepted and remains immutable',{skip:!enabled},async t=>{
  const f=await observationScope(t);assert.equal((await rawObservation(f.pool,f.observation)).rowCount,1);
  await assert.rejects(()=>f.pool.query('UPDATE searchad_commerce_observations SET complete=true'),/immutable/);
  await assert.rejects(()=>f.pool.query('DELETE FROM searchad_commerce_observations'),/immutable/);
  assert.equal((await f.pool.query('SELECT count(*)::int AS n FROM searchad_commerce_observations')).rows[0].n,1);
});
