import test from 'node:test';
import assert from 'node:assert/strict';
import { PostgresCircuitRepository } from '../src/naver/searchad/circuit/postgres-repository.js';
import { CircuitService } from '../src/naver/searchad/circuit/service.js';
import { CircuitProjectionService } from '../src/naver/searchad/circuit/projection-service.js';
import { postgresCompletionFixture } from './helpers/postgres-searchad-completion-fixture.js';
const at = Date.parse('2026-10-05T03:00:00Z');
const admin = { principal: { principalId: 'circuit-admin', role: 'admin', customerIds: ['1001'] } };
function required(t) { if (process.env.TEST_DATABASE_URL) return true; assert.notEqual(process.env.CI, 'true', 'CI requires native Circuit coverage'); t.skip('TEST_DATABASE_URL is required'); return false; }
test('duplicate_event_does_not_increment_failure_count; pause_is_sticky_across_midnight_and_restart', async t => {
  if (!required(t)) return;
  const f = await postgresCompletionFixture(t); await f.pool.query("INSERT INTO searchad_canary_accounts(customer_id) VALUES('1001')");
  let repository = new PostgresCircuitRepository({ pool: f.pool });
  const source = { customerId: '1001', sourceKind: 'write', sourceId: 'once', event: { logicalKey: 'write:p1:execute', outcome: 'failed', ruleId: 'r1', occurredAt: at }, now: at };
  assert.equal(await repository.projectOnce(source), true); assert.equal(await repository.projectOnce(source), false);
  assert.equal((await repository.getState({ customerId: '1001', now: at })).consecutiveFailures.r1, 1);
  const projection = new CircuitProjectionService({ repository, sources: [], clock: () => at });
  const circuit = new CircuitService({ repository, projection, clock: () => at });
  await circuit.pause({ customerId: '1001', reason: 'investigate spend' }, admin);
  repository = new PostgresCircuitRepository({ pool: f.connect() });
  assert.equal((await repository.getState({ customerId: '1001', now: at + 86400000 })).manualPaused, true);
  await assert.rejects(circuit.resume({ customerId: '1001', reason: 'ready' }, { principal: { ...admin.principal, customerIds: ['2002'] } }), { status: 403 });
  await assert.rejects(f.pool.query("UPDATE searchad_circuit_events SET event_json='{}'"), { code: 'P0001' });
});
test('source anti-join catches newly committed backdated outcome and canonical verification does not double count', async t => {
  if (!required(t)) return;
  const f = await postgresCompletionFixture(t); await f.pool.query("INSERT INTO searchad_canary_accounts(customer_id) VALUES('1001')");
  const repository = new PostgresCircuitRepository({ pool: f.pool });
  for (const [id, when] of [['later', at], ['backdated', at - 1000]]) await repository.projectOnce({ customerId: '1001', sourceKind: 'write', sourceId: id, event: { logicalKey: 'write:p1:execute', outcome: 'failed', ruleId: 'r1', occurredAt: when }, now: at });
  assert.equal((await repository.getState({ customerId: '1001', now: at })).consecutiveFailures.r1, 1);
});
test('real HTTP Circuit controls remain Customer scoped, sanitized and sticky after reporting-OFF restart', async t => {
  if (!required(t)) return;
  const { completionReaderKey } = await import('./helpers/postgres-searchad-completion-fixture.js');
  const f = await postgresCompletionFixture(t); const key = 'circuit-admin-test-'.repeat(4);
  const options = { appEnv: { ATELIER_SEARCHAD_REPORTING_ENABLED: 'false', ATELIER_HTTP_ALLOW_WRITES: 'true', ATELIER_SEARCHAD_ADMIN_API_KEY: key, ATELIER_SEARCHAD_ADMIN_CUSTOMERS: '1001', ATELIER_SEARCHAD_ADMIN_PRINCIPAL_ID: 'circuit-admin' } };
  const first = await f.start(options);
  assert.equal((await first.call(completionReaderKey, 'POST', '/api/v1/searchad/circuit/pause', { customerId: '1001', reason: 'hold' })).status, 403);
  assert.equal((await first.call(key, 'POST', '/api/v1/searchad/circuit/pause', { customerId: '2002', reason: 'hold' })).status, 403);
  assert.equal((await first.call(key, 'POST', '/api/v1/searchad/circuit/pause', { customerId: '1001', reason: 'hold', purpose: 'rollback' })).status, 400);
  assert.equal((await first.call(key, 'POST', '/api/v1/searchad/circuit/pause', { customerId: '1001', reason: 'investigate' })).status, 200);
  await first.api.close(); const restarted = await f.start(options);
  const status = await restarted.call(completionReaderKey, 'GET', '/api/v1/searchad/circuit?customerId=1001');
  assert.equal(status.status, 200); assert.equal(status.body.state.manualPaused, true); assert.equal(status.body.spendEvidenceAvailable, false);
  assert.equal((await restarted.call(key, 'POST', '/api/v1/searchad/circuit/resume', { customerId: '1001', reason: 'reviewed' })).status, 200);
  await f.pool.query('DROP TABLE searchad_circuit_state');
  const unavailable = await restarted.call(completionReaderKey, 'GET', '/api/v1/searchad/circuit?customerId=1001');
  assert.equal(unavailable.status, 503); assert.equal(JSON.stringify(unavailable.body).includes('SELECT'), false);
});
test('final guard sees late backdated source commits and excludes only its exact own ordinary plan', async t => {
  if (!required(t)) return;
  const { randomUUID } = await import('node:crypto');
  const { PostgresSearchAdWriteRepository } = await import('../src/naver/searchad/write/postgres-repository.js');
  const { createCircuitDispatch } = await import('../src/naver/searchad/circuit/service.js');
  const f = await postgresCompletionFixture(t); await f.pool.query("INSERT INTO searchad_canary_accounts(customer_id) VALUES('1001')");
  const writes = new PostgresSearchAdWriteRepository({ pool: f.pool });
  const plan = async status => { const id = randomUUID(); await writes.createPlan({ plan_id:id,customer_id:'1001',mutation_operation_key:'fixture',mutation_json:{operationKey:'fixture',pathParams:{campaignId:'c1'}},read_json:{},before_json:{},before_hash:'fixture',expected_after_json:{},reason:'fixture',status,created_by:'fixture',created_at:new Date(at).toISOString(),expires_at:new Date(at+600000).toISOString() }); return id; };
  const own = await plan('unknown_outcome'); const failed = await plan('failed');
  const repository = new PostgresCircuitRepository({ pool: f.pool }); const projection = new CircuitProjectionService({ repository, sources: repository.sources(), clock: () => at }); const circuit = new CircuitService({ repository, projection, clock: () => at });
  const dispatch = createCircuitDispatch({ customerId:'1001',purpose:'ordinary',operationKey:'fixture',entityType:'campaign',entityId:'c1',actionClass:'decrease' }, { planId:own });
  const assertAllowed = () => repository.transaction('1001', client => circuit.assertDispatchAllowed(dispatch, { client, now:at }));
  await circuit.prepareDispatch(dispatch); await assertAllowed();
  await writes.addAttempt({ attempt_id:randomUUID(),plan_id:failed,phase:'execute',status:'failed',created_at:new Date(at-86400000).toISOString() });
  await assert.rejects(assertAllowed(), error => error.details.reasons.includes('PROJECTION_BACKLOG'));
  await circuit.prepareDispatch(dispatch); await assertAllowed();
  await plan('unknown_outcome');
  await assert.rejects(assertAllowed(), error => error.details.reasons.includes('UNRESOLVED_MUTATION'));
});
test('neutral receipts never resolve unknown and only linked verified outcome resolves canonical mutation', async t => {
  if (!required(t)) return;
  const f = await postgresCompletionFixture(t); await f.pool.query("INSERT INTO searchad_canary_accounts(customer_id) VALUES('1001')");
  const repository = new PostgresCircuitRepository({ pool: f.pool });
  for (const [sourceId,outcome,key] of [['unknown','unknown','one'],['receipt','neutral','one'],['unlinked-read','succeeded','different']]) await repository.projectOnce({ customerId:'1001',sourceKind:'write',sourceId,event:{logicalKey:key,outcome,occurredAt:at},now:at });
  assert.equal((await repository.getState({customerId:'1001'})).unknownCount,1);
  await repository.projectOnce({customerId:'1001',sourceKind:'write',sourceId:'verified-after-hash',event:{logicalKey:'one',outcome:'succeeded',occurredAt:at},now:at});
  assert.equal((await repository.getState({customerId:'1001'})).unknownCount,0);
  await repository.projectOnce({customerId:'1001',sourceKind:'write',sourceId:'backdated-duplicate-ambiguity',event:{logicalKey:'one',outcome:'unknown',occurredAt:at-1000},now:at});
  assert.equal((await repository.getState({customerId:'1001'})).unknownCount,0);
});

test('neutral planning including an already projected legacy success cannot mask same-plan unknown outcome',async t=>{
  if(!required(t))return;
  const {randomUUID}=await import('node:crypto');const {PostgresSearchAdWriteRepository}=await import('../src/naver/searchad/write/postgres-repository.js');
  const f=await postgresCompletionFixture(t),writes=new PostgresSearchAdWriteRepository({pool:f.pool}),planId=randomUUID(),planningId=randomUUID();
  await writes.createPlan({plan_id:planId,customer_id:'1001',mutation_operation_key:'fixture',mutation_json:{pathParams:{campaignId:'c1'}},read_json:{},before_json:{},before_hash:'fixture',expected_after_json:{},reason:'fixture',status:'planned',created_by:'fixture',created_at:new Date(at).toISOString(),expires_at:new Date(at+600000).toISOString()});
  await writes.addAttempt({attempt_id:planningId,plan_id:planId,phase:'plan',status:'succeeded',created_at:new Date(at).toISOString()});
  const repository=new PostgresCircuitRepository({pool:f.pool});
  assert.deepEqual(await repository.unprojected({customerId:'1001',kind:'write'}),[],'planning audit is not a mutation backlog');
  await f.pool.query("INSERT INTO searchad_canary_accounts(customer_id) VALUES('1001')");
  await repository.projectOnce({customerId:'1001',sourceKind:'write',sourceId:planningId,event:{logicalKey:`write:${planId}:execute`,outcome:'succeeded',entityType:'campaign',entityId:'c1',occurredAt:at},now:at});
  await repository.projectOnce({customerId:'1001',sourceKind:'write',sourceId:'orphan-audit-kept',event:{logicalKey:'separate',outcome:'succeeded',entityType:'campaign',entityId:'orphan',occurredAt:at},now:at});
  await writes.addAttempt({attempt_id:randomUUID(),plan_id:planId,phase:'execute',status:'unknown_outcome',created_at:new Date(at).toISOString()});
  await writes.updatePlan(planId,{status:'unknown_outcome'});
  const projection=new CircuitProjectionService({repository,sources:repository.sources(),clock:()=>at});assert.equal((await projection.catchUp({customerId:'1001'})).ready,true);
  const state=await repository.getState({customerId:'1001',entityType:'campaign',entityId:'c1'});
  assert.equal(state.unknownCount,1);assert.equal(state.changedAt,null,'planning is never post-mutation observation authority');
  assert.equal((await repository.getState({customerId:'1001',entityType:'campaign',entityId:'orphan'})).changedAt,at,'unlinked immutable rows are not arbitrarily discarded');
  assert.equal((await f.pool.query("SELECT count(*)::int AS n FROM searchad_circuit_events WHERE source_id=$1",[planningId])).rows[0].n,1,'historical audit is retained');
});
