import test from 'node:test';
import assert from 'node:assert/strict';
import { postgresCompletionFixture } from './helpers/postgres-searchad-completion-fixture.js';
const enabled=Boolean(process.env.TEST_DATABASE_URL);
test('profitability and recommendation providers are wired in real runtime',{skip:!enabled},async t=>{const f=await postgresCompletionFixture(t);const {app}=await f.start();assert.ok(app.searchAdCompletionRuntime.profitabilityService);assert.ok(app.searchAdCompletionRuntime.recommendationService);assert.ok(app.searchAdCompletionRuntime.recommendationToolAdapter);});
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { completionReaderKey as reader, completionOperatorKey as operator } from './helpers/postgres-searchad-completion-fixture.js';
import { LocalReportStorage } from '../src/naver/searchad/reporting/blob-storage.js';
const admin='profit-admin-'.repeat(6);
const appEnv={ATELIER_COMMERCE_ALLOW_UNVERIFIED_OPERATIONS:'true',ATELIER_SEARCHAD_ALLOW_UNVERIFIED_OPERATIONS:'true',ATELIER_SEARCHAD_ADMIN_API_KEY:admin,ATELIER_SEARCHAD_ADMIN_CUSTOMERS:'1001',ATELIER_SEARCHAD_ADMIN_PRINCIPAL_ID:'profit-admin'};
const fixture=name=>JSON.parse(fs.readFileSync(`test/fixtures/searchad-profitability/${name}.json`));
async function setup(t,{report=false,cafe=false}={}){
  const f=await postgresCompletionFixture(t);let clock=Date.parse('2026-10-05T03:00:00Z'),remote=0,cost='110';const jobs=new Map();
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'profit-reports-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));
  const options={clock:()=>clock,blobStorage:new LocalReportStorage({root}),appEnv:{...appEnv,...(report?{ATELIER_SEARCHAD_ALLOW_REPORTING_JOBS:'true',ATELIER_SEARCHAD_REPORT_CLOCK_UNCERTAINTY_MS:'1000',ATELIER_SEARCHAD_REPORT_ROLLOUT_UNCERTAINTY_MS:'1000'}:{}),...(cafe?{CAFE24_MALL_ID:'fixturemall',CAFE24_CLIENT_ID:'fixture-cafe-app',CAFE24_CLIENT_SECRET:'fixture-cafe-secret',CAFE24_ACCESS_TOKEN:'fixture-cafe-access',CAFE24_ACCESS_TOKEN_EXPIRES_AT:'2030-01-01T00:00:00Z',CAFE24_TOKEN_STORE_PATH:path.join(root,'unused-token.json')}:{})},allowedPaths:['/keywordstool','/stat-reports','/stat-reports/1','/stat-reports/2','/stat-reports/3','/stat-reports/4','/report-download'],response:({target,init})=>{
    if(target.pathname==='/keywordstool')return Response.json({keywordList:[{relKeyword:'silver ring'}]});
    if(target.pathname==='/report-download')return new Response(`2026-10-01\t1001\tcmp-1\tgrp-1\tkw-1\tad-1\tbiz-1\t1\tP\t100\t2\t${cost}\t100\t0\n`);
    if(init.method==='POST'){const id=String(++remote);jobs.set(id,{reportJobId:remote,reportTp:'AD',statDt:'2026-09-30T15:00:00Z',status:'BUILT',updateTm:new Date(clock).toISOString(),downloadUrl:'https://api.searchad.naver.com/report-download?authtoken=fixture-report-secret&fileVersion=v2'});return Response.json(jobs.get(id));}
    return Response.json(jobs.get(target.pathname.split('/').at(-1)));
  }};
  const server=await f.start(options);const id=randomUUID();await f.pool.query("INSERT INTO haar_products(haar_product_id,product_name) VALUES($1,'silver ring')",[id]);
  const commerceCalls=[];server.app.client.tokenProvider.cached={accessToken:'fixture-commerce-token',issuedAt:Date.now(),expiresIn:3600};server.app.client.fetchImpl=async(url,init)=>{assert.equal(init.method,'GET');assert.equal(new URL(url).origin,'https://api.commerce.naver.com');const key={'/external/v2/products/channel-products/123':'naver-product','/external/v1/pay-order/seller/product-orders':'naver-orders','/external/v1/pay-settle/settle/case':'naver-settlements'}[new URL(url).pathname];assert.ok(key,'closed Commerce trap');commerceCalls.push(key);return Response.json(fixture(key));};
  if(cafe)server.app.searchAdCompletionRuntime.commerceProviders.get('haar_own_mall').client.fetchImpl=async(url,init)=>{assert.equal(init.method,'GET');assert.equal(new URL(url).origin,'https://fixturemall.cafe24api.com');assert.ok(['/api/v2/admin/products/123','/api/v2/admin/products/123/variants'].includes(new URL(url).pathname));return Response.json(fixture(new URL(url).pathname.endsWith('variants')?'cafe24-variants':'cafe24-product'));};
  const scope={customerId:'1001',haarProductId:id,since:'2026-10-01',until:'2026-10-01'};
  for(const channel of ['haar_naver_smartstore',...(cafe?['haar_own_mall']:[])]){await f.pool.query("INSERT INTO channel_products(channel_id,haar_product_id,channel_product_no,remote_product_id,channel_product_key,product_name) VALUES($1,$2,'123','123',$3,'ring')",[channel,id,`${channel}:123`]);assert.equal((await server.call(admin,'POST','/api/v1/searchad/customer-channel-bindings',{customerId:'1001',channelId:channel})).status,200);assert.equal((await server.call(admin,'POST','/api/v1/searchad/product-mappings',{customerId:'1001',haarProductId:id,channelProductKey:`${channel}:123`,entityType:'campaign',entityId:'cmp-1',method:'manual',validFrom:'2026-09-30T00:00:00Z'})).status,200);}
  const collect=()=>server.call(operator,'POST','/api/v1/searchad/product-evidence/collect',scope);
  const generate=()=>server.call(operator,'POST','/api/v1/searchad/recommendations/generate',scope);
  const read=()=>server.call(reader,'GET',`/api/v1/searchad/profitability/products/${id}?customerId=1001&since=2026-10-01&until=2026-10-01`);
  return {...f,...server,scope,id,options,collect,generate,read,commerceCalls,setTime:value=>clock=Date.parse(value),setCost:value=>cost=value};
}
test('native immutable snapshot, deterministic decisions, scoped Reader/Operator HTTP and restart',{skip:!enabled},async t=>{
  const f=await setup(t);assert.equal((await f.collect()).status,200);const first=await f.generate();assert.equal(first.status,200,JSON.stringify(first));assert.equal(first.body.recommendations.length,6);const second=await f.generate();assert.deepEqual(second.body,first.body);const s=await f.read();assert.equal(s.status,200,JSON.stringify(s));assert.equal(s.body.persisted,true);assert.equal(s.body.quality,'partial');assert.equal(s.body.metrics.netRevenueKrw,'7000');assert.equal(s.body.metrics.paidRevenueKrw,'14000');assert.equal(s.body.componentProvenance.returnProvision.deductedKrw,'0');assert.equal(s.body.metrics.contributionKrw,null);
  assert.equal((await f.pool.query('SELECT count(*)::int AS n FROM searchad_profitability_snapshots')).rows[0].n,1);assert.equal((await f.pool.query('SELECT count(*)::int AS n FROM searchad_recommendations')).rows[0].n,6);await assert.rejects(()=>f.pool.query("UPDATE searchad_profitability_snapshots SET quality='actual'"),/immutable/);await assert.rejects(()=>f.pool.query('DELETE FROM searchad_recommendations'),/immutable/);
  const route=`/api/v1/searchad/recommendations?customerId=1001&haarProductId=${f.id}&since=2026-10-01&until=2026-10-01`;assert.equal((await f.call(reader,'GET',route)).body.recommendations.length,6);await f.api.close();const restarted=await f.start(f.options);const persisted=await restarted.call(reader,'GET',route);assert.equal(persisted.status,200);assert.equal(persisted.body.recommendations.length,6);assert.ok(persisted.body.recommendations.every(r=>!r.executable&&!r.outcomeVerified));assert.equal((await restarted.call(reader,'POST','/api/v1/searchad/recommendations/generate',f.scope)).status,403);assert.equal((await restarted.call(reader,'GET',route.replace('1001','2002'))).status,403);assert.equal((await restarted.call(reader,'GET',`${route}&haarProductId=${randomUUID()}`)).status,400);
  const stored=JSON.stringify((await f.pool.query('SELECT snapshot_json FROM searchad_profitability_snapshots')).rows);for(const secret of ['PRIVATE_BUYER','01012345678','fixture-commerce-token','fixture-report-secret','order-1'])assert.equal(stored.includes(secret),false);
});
test('HTTP cannot supply money, identity, source hashes, quality or execution authority',{skip:!enabled},async t=>{const f=await setup(t);for(const payload of [{components:{}},{quality:'actual'},{inputHash:'a'.repeat(64)},{identityHash:'b'.repeat(64)},{executable:true},{mappingVerified:true},{provider:{trusted:true}},{since:'2026-02-30'}]){const r=await f.call(operator,'POST','/api/v1/searchad/recommendations/generate',{...f.scope,...payload});assert.equal(r.status,400,JSON.stringify(payload));}assert.equal(f.calls.length,0);assert.equal((await f.pool.query('SELECT count(*)::int AS n FROM searchad_profitability_snapshots')).rows[0].n,0);});
test('rotated provider binding and remapping cannot reuse persisted profit or recommendations',{skip:!enabled},async t=>{const f=await setup(t);await f.collect();const old=await f.generate();assert.equal(old.status,200,JSON.stringify(old));f.app.searchAdCompletionRuntime.commerceProviders.get('haar_naver_smartstore').sourceIdentity='f'.repeat(64);await f.call(admin,'POST','/api/v1/searchad/customer-channel-bindings',{customerId:'1001',channelId:'haar_naver_smartstore'});assert.equal((await f.read()).status,409);assert.equal((await f.generate()).status,409);await f.call(admin,'POST','/api/v1/searchad/product-mappings',{customerId:'1001',haarProductId:f.id,channelProductKey:'haar_naver_smartstore:123',entityType:'campaign',entityId:'cmp-1',method:'manual',validFrom:'2026-09-30T01:00:00Z'});const fresh=await f.read();assert.equal(fresh.status,200);assert.equal(fresh.body.metrics.netRevenueKrw,null);assert.notEqual(fresh.body.inputHash,old.body.inputHash);assert.equal(fresh.body.persisted,false);await f.collect();const current=await f.generate();assert.equal(current.status,200,JSON.stringify(current));assert.notEqual(current.body.snapshotId,old.body.snapshotId);assert.equal((await f.pool.query('SELECT count(DISTINCT observed_at)::int AS n FROM searchad_commerce_observations')).rows[0].n,1);});
test('real repeated ingestion/recollection and two channel mappings never duplicate shared spend',{skip:!enabled},async t=>{
  const f=await setup(t,{report:true,cafe:true});
  for(const day of [2,3,4]){f.setTime(`2026-10-0${day}T03:00:00Z`);const created=await f.call(operator,'POST','/api/v1/searchad/reporting/jobs',{customerId:'1001',kind:'stat',reportType:'AD',statDate:'2026-10-01',intentKey:`profit-${day}`});assert.equal(created.status,201,JSON.stringify(created));const route=`/api/v1/searchad/reporting/jobs/${created.body.reportJobId}/ingest`;assert.equal((await f.call(operator,'POST',route,{customerId:'1001'})).status,200);assert.equal((await f.call(operator,'POST',route,{customerId:'1001'})).status,200);}
  await f.collect();const a=await f.generate();assert.equal(a.status,200,JSON.stringify(a));const s=await f.read();assert.equal(s.body.sources.ads.filter(g=>g.reportType==='AD').length,1);assert.equal(s.body.unallocatedSpendKrw,'110');assert.equal(s.body.metrics.adCostKrw,null);assert.equal(s.body.metrics.netRevenueKrw,'7000');assert.equal(s.body.observations.length,8);assert.equal(s.body.quality,'partial');assert.ok(s.body.missingReasons.includes('CAFE24_ORDERLINES_CAPABILITY_UNVERIFIED')||s.body.missingReasons.some(x=>x.startsWith('CAFE24_')));const again=await f.generate();assert.deepEqual(again.body,a.body);assert.equal((await f.pool.query('SELECT count(*)::int AS n FROM searchad_daily_metrics')).rows[0].n,3);
});
test('multiple suppliers, identical SKUs and variant costs remain distinct and cannot fake COGS',{skip:!enabled},async t=>{const f=await setup(t);await f.collect();for(const [source,cost]of [['supplier-a','100'],['supplier-b','900']]){await f.pool.query("INSERT INTO catalog_sources(source_id,source_name,source_type,provider_type) VALUES($1,$1,'supplier','manual_upload')",[source]);await f.pool.query("INSERT INTO source_products(source_id,source_product_id,source_product_name) VALUES($1,'SKU-SAME','source ring')",[source]);await f.pool.query("INSERT INTO haar_product_source_links(haar_product_id,source_id,source_product_id,valid_from) VALUES($1,$2,'SKU-SAME','2026-09-01')",[f.id,source]);await f.pool.query("INSERT INTO supplier_cost_history(source_id,source_product_id,supply_cost,effective_from) VALUES($1,'SKU-SAME',$2,'2026-09-01')",[source,cost]);}
  const first=await f.read();assert.equal(first.body.sourceCosts.length,2);assert.notEqual(first.body.sourceCosts[0].sourceReference,first.body.sourceCosts[1].sourceReference);assert.equal(first.body.metrics.cogsKrw,null);assert.ok(first.body.missingReasons.includes('SUPPLIER_COST_ASSIGNMENT_UNRESOLVED'));
  const variant=randomUUID();await f.pool.query('INSERT INTO haar_product_variants(haar_variant_id,haar_product_id) VALUES($1,$2)',[variant,f.id]);assert.equal((await f.call(admin,'POST','/api/v1/searchad/product-costs',{customerId:'1001',haarProductId:f.id,haarVariantId:variant,component:'cogs',amountKrw:'500',sourceReference:'variant-specific',reason:'manual estimate',validFrom:'2026-09-01T00:00:00Z'})).status,200);const second=await f.read();assert.equal(second.body.metrics.cogsKrw,null);assert.ok(second.body.missingReasons.includes('VARIANT_COST_ASSIGNMENT_UNRESOLVED'));assert.notEqual(second.body.inputHash,first.body.inputHash);
});
test('manual effective costs are estimated per remaining unit and never produce actual quality',{skip:!enabled},async t=>{const f=await setup(t);await f.collect();for(const [component,amountKrw]of [['cogs','3000'],['fees','100'],['shipping','500'],['return_provision','50']])assert.equal((await f.call(admin,'POST','/api/v1/searchad/product-costs',{customerId:'1001',haarProductId:f.id,component,amountKrw,sourceReference:'manual-source',reason:'per unit estimate',validFrom:'2026-09-01T00:00:00Z'})).status,200);const result=await f.generate();assert.equal(result.status,200,JSON.stringify(result));const s=await f.read();assert.equal(s.body.metrics.cogsKrw,'3000');assert.equal(s.body.quality,'partial');assert.equal(s.body.componentProvenance.returnProvision.deductedKrw,'50');assert.ok(result.body.recommendations.every(r=>r.executable===false));});
test('second configured Customer cannot read first Customer canonical snapshots through its own token',{skip:!enabled},async t=>{const f=await setup(t);await f.collect();assert.equal((await f.generate()).status,200);const otherKey='second-customer-reader-'.repeat(3);const other=await f.start({appEnv:{...appEnv,NAVER_SEARCHAD_CUSTOMER_ID:'2002',ATELIER_SEARCHAD_READER_API_KEY:otherKey,ATELIER_SEARCHAD_READER_CUSTOMERS:'2002'}});const route=`/api/v1/searchad/profitability/products/${f.id}?customerId=2002&since=2026-10-01&until=2026-10-01`;const denied=await other.call(otherKey,'GET',route);assert.equal(denied.status,409,JSON.stringify(denied));assert.equal(JSON.stringify(denied.body).includes('7000'),false);assert.equal((await other.call(otherKey,'GET',route.replace('customerId=2002','customerId=1001'))).status,403);});
test('historical cost interval and single supplier variant are not assigned without order-line provenance',{skip:!enabled},async t=>{const f=await setup(t);await f.collect();const cost={customerId:'1001',haarProductId:f.id,component:'cogs',amountKrw:'1000',sourceReference:'late-cost',reason:'effective after sales',validFrom:'2026-10-02T00:00:00Z'};assert.equal((await f.call(admin,'POST','/api/v1/searchad/product-costs',cost)).status,200);assert.equal((await f.read()).body.metrics.cogsKrw,null);
  const variant=randomUUID();await f.pool.query('INSERT INTO haar_product_variants(haar_variant_id,haar_product_id) VALUES($1,$2)',[variant,f.id]);await f.pool.query("INSERT INTO catalog_sources(source_id,source_name,source_type,provider_type) VALUES('source-a','source a','supplier','manual_upload')");await f.pool.query("INSERT INTO source_products(source_id,source_product_id,source_product_name) VALUES('source-a','SKU','source ring')");await f.pool.query("INSERT INTO source_product_variants(source_id,source_product_id,source_variant_id) VALUES('source-a','SKU','V1')");await f.pool.query("INSERT INTO haar_product_source_links(haar_product_id,source_id,source_product_id,valid_from) VALUES($1,'source-a','SKU','2026-09-01')",[f.id]);await f.pool.query("INSERT INTO source_variant_links(haar_variant_id,source_id,source_product_id,source_variant_id,valid_from) VALUES($1,'source-a','SKU','V1','2026-09-01')",[variant]);await f.pool.query("INSERT INTO supplier_cost_history(source_id,source_product_id,source_variant_id,supply_cost,effective_from) VALUES('source-a','SKU','V1',500,'2026-09-01')");const s=await f.read();assert.equal(s.body.sourceCosts.length,1);assert.equal(s.body.sourceCosts[0].variantSpecific,true);assert.equal(s.body.metrics.cogsKrw,null);assert.ok(s.body.missingReasons.includes('VARIANT_COST_ASSIGNMENT_UNRESOLVED'));
});
test('case-equivalent canonical UUID has identical HTTP snapshot/hash/recommendation IDs',{skip:!enabled},async t=>{const f=await setup(t);await f.collect();const lower=await f.generate();assert.equal(lower.status,200);const upper=await f.call(operator,'POST','/api/v1/searchad/recommendations/generate',{...f.scope,haarProductId:f.id.toUpperCase()});assert.equal(upper.status,200,JSON.stringify(upper));assert.deepEqual(upper.body,lower.body);const listed=await f.call(reader,'GET',`/api/v1/searchad/recommendations?customerId=1001&haarProductId=${f.id.toUpperCase()}&since=2026-10-01&until=2026-10-01`);assert.equal(listed.status,200);assert.equal(listed.body.recommendations.length,6);assert.equal((await f.pool.query('SELECT count(*)::int AS n FROM searchad_profitability_snapshots')).rows[0].n,1);assert.equal((await f.pool.query('SELECT count(*)::int AS n FROM searchad_recommendations')).rows[0].n,6);});

// Simulate the catalog importer's committed PG projection, without a live import.
async function syncCatalog(f,stock){
  const run=(await f.pool.query("INSERT INTO channel_import_runs(channel_id,mode,status,idempotency_key,request_hash) VALUES('haar_naver_smartstore','single','succeeded',$1,$1) RETURNING import_run_id",[randomUUID()])).rows[0].import_run_id;
  const row=(await f.pool.query(`INSERT INTO channel_product_snapshots(channel_product_id,import_run_id,raw_json,normalized_json,content_hash) SELECT channel_product_id,$2,'{}',$3,$4 FROM channel_products WHERE haar_product_id=$1 AND channel_id='haar_naver_smartstore' RETURNING snapshot_id,channel_product_id`,[f.id,run,JSON.stringify({channelStatus:'SALE',stockQuantity:stock}),randomUUID()])).rows[0];
  await f.pool.query('UPDATE channel_products SET latest_snapshot_id=$1,last_synced_at=$2 WHERE channel_product_id=$3',[row.snapshot_id,'2026-10-05T03:00:00Z',row.channel_product_id]);
}
test('T9-I1 native catalog sync changes immutable identity and survives regeneration/restart',{skip:!enabled},async t=>{
  const f=await setup(t,{cafe:true});await f.collect();await syncCatalog(f,10);const first=await f.generate();assert.equal(first.status,200);const old=await f.read();
  await syncCatalog(f,9);const current=await f.read();assert.equal(current.status,200,JSON.stringify(current));assert.equal(current.body.persisted,false);for(const key of ['inputHash','sourceSetHash','snapshotId'])assert.notEqual(current.body[key],old.body[key],key);assert.equal(current.body.catalog.find(c=>c.stockQuantity!==null).stockQuantity,'9');assert.deepEqual(current.body.catalog.map(c=>c.channelProductId),current.body.catalog.map(c=>c.channelProductId).sort());assert.equal((await f.call(reader,'GET',`/api/v1/searchad/recommendations?customerId=1001&haarProductId=${f.id}&since=2026-10-01&until=2026-10-01`)).body.recommendations.length,0);
  const fresh=await f.generate();assert.equal(fresh.status,200);assert.notEqual(fresh.body.snapshotId,first.body.snapshotId);assert.deepEqual((await f.generate()).body,fresh.body);
  const history=(await f.pool.query('SELECT snapshot_json FROM searchad_profitability_snapshots')).rows;assert.equal(history.length,2);assert.equal(history.find(x=>x.snapshot_json.snapshotId===old.body.snapshotId).snapshot_json.catalog.find(c=>c.stockQuantity!==null).stockQuantity,'10');
  await f.api.close();const restarted=await f.start(f.options);const read=await restarted.call(reader,'GET',`/api/v1/searchad/profitability/products/${f.id}?customerId=1001&since=2026-10-01&until=2026-10-01`);assert.equal(read.status,200);assert.equal(read.body.snapshotId,fresh.body.snapshotId);assert.equal(read.body.persisted,true);
});
for(const [name,value,raw,canonical] of [['fractional',1.2,null,null],['unsafe',Number.MAX_SAFE_INTEGER+1,null,null],['integer',1200,'1200','1200'],['decimal string','1.2000','1.2000','1.2']])test(`T9-I2 real provider/DB/HTTP ${name} money`,{skip:!enabled},async t=>{
  const f=await setup(t),previous=f.app.client.fetchImpl;f.app.client.fetchImpl=async(...args)=>{const response=await previous(...args);if(new URL(args[0]).pathname!=='/external/v1/pay-order/seller/product-orders')return response;const data=await response.json();for(const item of data.data.contents)if(item.content.productOrder.productId==='123'){item.content.productOrder.initialPaymentAmount=value;item.content.productOrder.remainPaymentAmount=value;}return Response.json(data);};
  assert.equal((await f.collect()).status,200);const observation=(await f.pool.query("SELECT rows_json,complete,missing_reasons FROM searchad_commerce_observations WHERE capability='orderLines'")).rows[0];assert.equal(observation.rows_json[0].netRevenueKrw,raw);assert.equal(observation.complete,raw!==null);assert.equal(observation.missing_reasons.includes('ORDER_FIELDS_MISSING'),raw===null);
  assert.equal((await f.generate()).status,200);const s=await f.read();assert.equal(s.body.metrics.netRevenueKrw,canonical);assert.equal(s.body.componentProvenance.netRevenue.amountKrw,canonical);assert.equal(s.body.observations.find(o=>o.capability==='orderLines').rows[0].netRevenueKrw,raw);assert.ok(['partial','unknown'].includes(s.body.quality));
});
async function addCost(f,{amountKrw='100',validFrom='2026-09-01T00:00:00Z',validTo=null,component='cogs'}={}){const r=await f.call(admin,'POST','/api/v1/searchad/product-costs',{customerId:'1001',haarProductId:f.id,component,amountKrw,sourceReference:'historical estimate',reason:'interval regression',validFrom,validTo});assert.equal(r.status,200,JSON.stringify(r));}
async function addSupplier(f,{variant=false,linkFrom='2026-09-01T00:00:00Z',linkTo=null,variantFrom='2026-09-01T00:00:00Z',replacement=true}={}){
  await f.pool.query("INSERT INTO catalog_sources(source_id,source_name,source_type,provider_type) VALUES('historical-source','source','supplier','manual_upload')");await f.pool.query("INSERT INTO source_products(source_id,source_product_id,source_product_name) VALUES('historical-source','SKU','ring')");
  await f.pool.query("INSERT INTO haar_product_source_links(haar_product_id,source_id,source_product_id,valid_from,valid_to,created_at) VALUES($1,'historical-source','SKU',$2,$3,'2026-10-05')",[f.id,linkFrom,linkTo]);
  if(variant){const id=randomUUID();await f.pool.query('INSERT INTO haar_product_variants(haar_variant_id,haar_product_id) VALUES($1,$2)',[id,f.id]);await f.pool.query("INSERT INTO source_product_variants(source_id,source_product_id,source_variant_id) VALUES('historical-source','SKU','V1')");await f.pool.query("INSERT INTO source_variant_links(haar_variant_id,source_id,source_product_id,source_variant_id,valid_from,created_at) VALUES($1,'historical-source','SKU','V1',$2,'2026-10-05')",[id,variantFrom]);}
  await f.pool.query("INSERT INTO supplier_cost_history(source_id,source_product_id,source_variant_id,supply_cost,effective_from,effective_to) VALUES('historical-source','SKU',$1,100,'2026-09-01',$2)",[variant?'V1':null,replacement?'2026-10-02':null]);
  if(replacement)await f.pool.query("INSERT INTO supplier_cost_history(source_id,source_product_id,source_variant_id,supply_cost,effective_from) VALUES('historical-source','SKU',$1,900,'2026-10-02')",[variant?'V1':null]);
}
test('T9-I3 expired historical manual cost survives replacement after sales while current binding stays required',{skip:!enabled},async t=>{const f=await setup(t);await f.collect();await addCost(f,{validTo:'2026-10-02T00:00:00Z'});await addCost(f,{amountKrw:'900',validFrom:'2026-10-02T00:00:00Z'});const s=await f.read();assert.equal(s.body.metrics.cogsKrw,'100');assert.equal(s.body.costs.length,1);assert.equal(s.body.costs[0].validTo,'2026-10-02T00:00:00.000Z');f.app.searchAdCompletionRuntime.commerceProviders.get('haar_naver_smartstore').sourceIdentity='f'.repeat(64);assert.equal((await f.read()).status,409);});
test('T9-I3 expired historical supplier cost and source link cover sales before later replacement',{skip:!enabled},async t=>{const f=await setup(t);await f.collect();await addSupplier(f,{linkTo:'2026-10-02T00:00:00Z'});const s=await f.read();assert.equal(s.body.metrics.cogsKrw,'100');assert.equal(s.body.sourceCosts.length,1);assert.equal(s.body.sourceCosts[0].sourceLink.validTo,'2026-10-02T00:00:00.000Z');});
for(const [name,options,reason] of [['source link after sales',{linkFrom:'2026-10-02T00:00:00Z'},'SOURCE_COST_LINK_RANGE_PARTIAL'],['undated link created after sales',{linkFrom:null},'SOURCE_COST_LINK_RANGE_PARTIAL'],['variant link after sales',{variant:true,variantFrom:'2026-10-02T00:00:00Z'},'SOURCE_COST_LINK_RANGE_PARTIAL'],['source link expires during sales',{linkTo:'2026-10-01T03:00:00Z'},'SOURCE_COST_LINK_RANGE_PARTIAL']])test(`T9-I3 ${name} cannot assign historical cost`,{skip:!enabled},async t=>{const f=await setup(t);await f.collect();await addSupplier(f,{...options,replacement:false});const s=await f.read();assert.equal(s.body.metrics.cogsKrw,null);assert.ok(s.body.missingReasons.includes(reason),JSON.stringify(s.body.missingReasons));assert.equal(s.body.sourceCosts.length,1);assert.ok(s.body.sourceCosts[0].sourceLink);});
test('T9-I3 overlapping manual revisions and partial day coverage stay explicit and missing',{skip:!enabled},async t=>{const f=await setup(t);await f.collect();await addCost(f);await addCost(f,{amountKrw:'900',validFrom:'2026-09-15T00:00:00Z'});await addCost(f,{component:'fees',validFrom:'2026-10-01T03:00:00Z'});const s=await f.read();assert.equal(s.body.metrics.cogsKrw,null);assert.equal(s.body.metrics.feesKrw,null);assert.ok(s.body.missingReasons.includes('COGS_COST_INTERVAL_AMBIGUOUS'));assert.ok(s.body.missingReasons.includes('FEES_COST_RANGE_PARTIAL'));});

test('T9-I3 overlapping supplier costs and a partial cost range cannot supply COGS',{skip:!enabled},async t=>{const f=await setup(t);await f.collect();await addSupplier(f,{replacement:false});await f.pool.query("INSERT INTO supplier_cost_history(source_id,source_product_id,supply_cost,effective_from) VALUES('historical-source','SKU',200,'2026-10-01T03:00:00Z')");const s=await f.read();assert.equal(s.body.metrics.cogsKrw,null);assert.equal(s.body.sourceCosts.length,2);assert.ok(s.body.missingReasons.includes('SUPPLIER_COST_INTERVAL_AMBIGUOUS'));assert.ok(s.body.missingReasons.includes('SOURCE_COST_RANGE_PARTIAL'));});

for(const [name,linkFrom,linkTo,variant,expected] of [
  ['future supplier','2026-10-02T00:00:00Z',null,false,'100'],
  ['expired supplier','2026-09-01T00:00:00Z','2026-09-30T00:00:00Z',false,'100'],
  ['future variant link','2026-10-02T00:00:00Z',null,true,'100'],
  ['expired variant link','2026-09-01T00:00:00Z','2026-09-30T00:00:00Z',true,'100'],
  ['partially intersecting supplier','2026-10-01T03:00:00Z',null,false,null],
  ['truly overlapping supplier','2026-09-01T00:00:00Z',null,false,null]
])test(`T9-I3 fix2 applicable historical supplier plus ${name}`,{skip:!enabled},async t=>{
  const f=await setup(t);await f.collect();await addSupplier(f,{linkTo:'2026-10-02T00:00:00Z',replacement:false});assert.equal((await f.read()).body.metrics.cogsKrw,'100');
  await f.pool.query("INSERT INTO catalog_sources(source_id,source_name,source_type,provider_type) VALUES('other-source','other','supplier','manual_upload')");await f.pool.query("INSERT INTO source_products(source_id,source_product_id,source_product_name) VALUES('other-source','SKU','other ring')");
  await f.pool.query("INSERT INTO haar_product_source_links(haar_product_id,source_id,source_product_id,valid_from,valid_to) VALUES($1,'other-source','SKU',$2,$3)",[f.id,variant?'2026-09-01T00:00:00Z':linkFrom,variant?null:linkTo]);
  if(variant){const id=randomUUID();await f.pool.query('INSERT INTO haar_product_variants(haar_variant_id,haar_product_id) VALUES($1,$2)',[id,f.id]);await f.pool.query("INSERT INTO source_product_variants(source_id,source_product_id,source_variant_id) VALUES('other-source','SKU','V1')");await f.pool.query("INSERT INTO source_variant_links(haar_variant_id,source_id,source_product_id,source_variant_id,valid_from,valid_to) VALUES($1,'other-source','SKU','V1',$2,$3)",[id,linkFrom,linkTo]);}
  await f.pool.query("INSERT INTO supplier_cost_history(source_id,source_product_id,source_variant_id,supply_cost,effective_from) VALUES('other-source','SKU',$1,900,'2026-09-01')",[variant?'V1':null]);
  const s=await f.read();assert.equal(s.status,200);assert.equal(s.body.metrics.cogsKrw,expected);assert.equal(s.body.sourceCosts.length,2,'descriptive history retains the disjoint relationship');
  if(expected!==null){assert.equal(s.body.missingReasons.includes('SUPPLIER_COST_ASSIGNMENT_UNRESOLVED'),false);assert.equal(s.body.missingReasons.includes('SOURCE_COST_LINK_RANGE_PARTIAL'),false);assert.equal(s.body.missingReasons.includes('VARIANT_COST_ASSIGNMENT_UNRESOLVED'),false);}else assert.ok(s.body.missingReasons.includes('SUPPLIER_COST_ASSIGNMENT_UNRESOLVED'));
  if(name==='partially intersecting supplier')assert.ok(s.body.missingReasons.includes('SOURCE_COST_LINK_RANGE_PARTIAL'));
});
