import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import fs from 'node:fs';
import os from 'node:os';
import { randomUUID } from 'node:crypto';
import { createPostgresPool, closePostgresPool } from '../src/infrastructure/postgres/pool.js';
import { runPostgresMigrations, listMigrationFiles } from '../src/infrastructure/postgres/migrator.js';
import { PostgresReportingRepository } from '../src/naver/searchad/reporting/postgres-repository.js';
import { StatsObservationService } from '../src/naver/searchad/reporting/stats-service.js';
import { reportingFixture, input, context, now } from './helpers/searchad-completion-fixture.js';
const logger = { info() {}, warn() {}, error() {} };
test('reporting observations remain immutable Customer scoped and provisional after PostgreSQL reconnect', async t => {
  if (!process.env.TEST_DATABASE_URL) { assert.notEqual(process.env.CI, 'true', 'CI requires real PostgreSQL reporting coverage'); return t.skip('TEST_DATABASE_URL is required'); }
  const schema = `reporting_${randomUUID().replaceAll('-', '')}`;
  const admin = createPostgresPool({ connectionString: process.env.TEST_DATABASE_URL, sslMode: 'disable', logger });
  let pool;
  const historicalDir = fs.mkdtempSync(path.join(os.tmpdir(), 'haar-reporting-0009-'));
  try {
    await admin.query(`CREATE SCHEMA "${schema}"`);
    const url = new URL(process.env.TEST_DATABASE_URL); url.searchParams.set('options', `-csearch_path=${schema} -ctimezone=UTC`);
    const connect = () => createPostgresPool({ connectionString: url.toString(), sslMode: 'disable', logger });
    pool = connect();
    const migrationsDir = path.resolve('migrations/postgres');
    for (const migration of listMigrationFiles(migrationsDir).filter(file => file.version <= '0009')) fs.copyFileSync(path.join(migrationsDir, migration.fileName), path.join(historicalDir, migration.fileName));
    assert.equal((await runPostgresMigrations({ pool, migrationsDir: historicalDir, logger })).currentVersion, '0009');
    await pool.query("INSERT INTO searchad_customer_accounts(customer_id) VALUES('1001'),('2002')");
    const legacyJob = randomUUID();
    await pool.query("INSERT INTO searchad_report_jobs(report_job_id,customer_id,report_type,state,metadata_json) VALUES($1,'1001','AD','legacy_state','{\"historical\":true}')", [legacyJob]);
    const historicalChecksums = (await pool.query('SELECT version,checksum FROM schema_migrations ORDER BY version')).rows;
    assert.deepEqual(await runPostgresMigrations({ pool, migrationsDir, logger }), { applied: ['0010_searchad_reporting.sql', '0011_searchad_reporting_generation.sql', '0012_searchad_circuit_automation.sql', '0013_searchad_automation_protocol.sql', '0014_searchad_worker.sql', '0015_searchad_profitability.sql'], currentVersion: '0015' });
    assert.deepEqual((await pool.query("SELECT version,checksum FROM schema_migrations WHERE version <= '0009' ORDER BY version")).rows, historicalChecksums);
    assert.deepEqual((await pool.query('SELECT state,metadata_json,processing_state,quality FROM searchad_report_jobs WHERE report_job_id=$1', [legacyJob])).rows[0], { state: 'legacy_state', metadata_json: { historical: true }, processing_state: null, quality: null });
    assert.deepEqual(await runPostgresMigrations({ pool, migrationsDir, logger }), { applied: [], currentVersion: '0015' });
    const repository = new PostgresReportingRepository({ pool, clock: () => now });
    const f = reportingFixture({ repository });
    const observation = await new StatsObservationService({ ...f, clock: () => now }).collect(input, context);
    assert.equal(observation.metrics.spendGrossKrw, '1100'); assert.equal(observation.quality, 'provisional');
    await assert.rejects(() => pool.query('UPDATE searchad_stats_observations SET quality=$1 WHERE observation_id=$2', ['stabilized_by_policy', observation.observationId]), { code: 'P0001' });
    await assert.rejects(() => pool.query('DELETE FROM searchad_stats_observations WHERE observation_id=$1', [observation.observationId]), { code: 'P0001' });
    await closePostgresPool(pool); pool = connect();
    const restarted = new PostgresReportingRepository({ pool, clock: () => now });
    assert.deepEqual(await restarted.getObservation({ customerId: '1001', observationId: observation.observationId }), observation);
    assert.equal(await restarted.getObservation({ customerId: '2002', observationId: observation.observationId }), null);
    assert.deepEqual(await restarted.listObservations({ customerId: '2002', limit: 10 }), []);
    assert.equal((await restarted.listObservations({ customerId: '1001', entityType: 'campaign', entityId: 'cmp-1', limit: 10 })).length, 1);
    assert.equal(await restarted.findLatestTrustedObservation({ customerId: '1001', entityType: 'campaign', entityId: 'cmp-1', identity: f.identityResolver('1001'), now, maxAgeMs: 30000 }), null);
    const job = randomUUID();
    await pool.query("INSERT INTO searchad_report_jobs(report_job_id,customer_id,report_type,state,report_kind,intent_key,intent_hash) VALUES($1,'1001','AD','planned','stat','fixture-intent',$2)", [job, 'a'.repeat(64)]);
    await assert.rejects(() => pool.query("INSERT INTO searchad_report_blobs(blob_id,customer_id,report_job_id,blob_key,sha256,size_bytes,content_type,retain_until) VALUES($1,'2002',$2,'2002/fixture',$3,1,'text/tab-separated-values',now()+interval '2 years')", [randomUUID(), job, 'b'.repeat(64)]), { code: '23503' });
  } finally { await closePostgresPool(pool); await admin.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`); await closePostgresPool(admin); fs.rmSync(historicalDir, { recursive: true, force: true }); }
});
test('actual completion bootstrap HTTP retains observations across reconstruction with read and collect roles', async t => {
  if (!process.env.TEST_DATABASE_URL) { assert.notEqual(process.env.CI, 'true', 'CI requires real application reporting restart coverage'); return t.skip('TEST_DATABASE_URL is required'); }
  const { postgresCompletionFixture, completionReaderKey: reader, completionOperatorKey: operator } = await import('./helpers/postgres-searchad-completion-fixture.js');
  const f = await postgresCompletionFixture(t);
  const first = await f.start();
  assert.equal(first.app.searchAdCompletionStartupError, null); assert.equal(first.api.readiness().searchAdCompletion.ready, true);
  assert.equal(first.app.searchAdCompletionRuntime.repository.pool, first.app.searchAdActivationRuntime.repository.pool);
  const collected = await first.call(operator, 'POST', '/api/v1/searchad/reporting/stats', input);
  assert.equal(collected.status, 201, JSON.stringify(collected)); assert.equal(collected.body.metrics.spendGrossKrw, '1100'); assert.equal(collected.body.observedAt, '2026-10-05T03:00:00.000Z');
  assert.equal(JSON.stringify(collected.body).includes('credentialFingerprint'), false);
  assert.equal((await first.call(reader, 'POST', '/api/v1/searchad/reporting/stats', input)).status, 403);
  assert.equal((await first.call(operator, 'POST', '/api/v1/searchad/reporting/stats', { ...input, evidence: {} })).status, 400);
  const metrics = await first.call(reader, 'GET', '/api/v1/searchad/reporting/metrics?customerId=1001');
  assert.equal(metrics.status, 200); assert.deepEqual(metrics.body, { available: false, status: 'unavailable', reason: 'REPORT_INGESTION_REQUIRED', items: [] });
  await Promise.all([first.api.close(), first.api.close()]);
  await assert.rejects(() => first.app.searchAdCompletionRuntime.repository.listObservations({ customerId: '1001', limit: 1 }), { code: 'SEARCHAD_REPORTING_STORAGE_FAILED' });
  assert.equal((await f.pool.query('SELECT 1 AS alive')).rows[0].alive, 1);
  const second = await f.start();
  const read = await second.call(reader, 'GET', `/api/v1/searchad/reporting/observations/${collected.body.observationId}?customerId=1001`);
  assert.equal(read.status, 200); assert.deepEqual(read.body, collected.body);
  assert.equal((await second.call(reader, 'GET', `/api/v1/searchad/reporting/observations/${collected.body.observationId}?customerId=2002`)).status, 403);
  const listed = await second.call(reader, 'GET', '/api/v1/searchad/reporting/observations?customerId=1001&entityType=campaign&entityId=cmp-1'); assert.equal(listed.body.items.length, 1);
  assert.equal(f.calls.length, 1); assert.equal(second.app.searchAdConfig.allowWrites, false); assert.equal(second.app.searchAdConfig.allowActiveCanary, false);
  await second.api.close();
  const missingDatabase = await f.start({ appEnv: { DATABASE_URL: '' } });
  assert.equal(missingDatabase.app.searchAdCompletionStartupError.code, 'SEARCHAD_REPORTING_DATABASE_REQUIRED');
  assert.equal((await missingDatabase.call(reader, 'GET', '/api/v1/searchad/reporting/observations?customerId=1001')).status, 503);
  await missingDatabase.api.close();
});
