import test from 'node:test';
import assert from 'node:assert/strict';
import { validateMapping, normalizeAllocation, money, safeRows } from '../src/naver/searchad/profitability/contracts.js';
import { NaverCommerceEvidenceProvider, NAVER_EVIDENCE_READS } from '../src/naver/searchad/profitability/naver-commerce-provider.js';
import { Cafe24CommerceEvidenceProvider } from '../src/naver/searchad/profitability/cafe24-commerce-provider.js';
import { loadCommerceManifest } from '../src/naver/commerce/spec.js';
import fs from 'node:fs';
const haarProductId='00000000-0000-4000-8000-000000000001', other='00000000-0000-4000-8000-000000000002';
const mapping={customerId:'1001',haarProductId,channelProductKey:'haar_naver_smartstore:123',entityType:'campaign',entityId:'cmp-1',method:'manual'};
const scope={customerId:'1001',channelId:'haar_naver_smartstore',channelProductId:other,remoteProductId:'123',since:'2026-10-01',until:'2026-10-01'};
const clock=()=>Date.parse('2026-10-02T00:00:00Z');
const fixture=name=>JSON.parse(fs.readFileSync(new URL(`./fixtures/searchad-profitability/${name}.json`,import.meta.url)));
function naver(payloads){const calls=[];const manifest=loadCommerceManifest();const gateway={get:id=>manifest.operations.find(x=>x.operationId===id),async execute(id,input,context){calls.push({id,input,context});return {data:structuredClone(payloads[id] || {})};}};return {provider:new NaverCommerceEvidenceProvider({gateway,sourceIdentity:'a'.repeat(64),clock}),calls};}
test('canonical_uuid_and_text_channel_key_are_not_confused',()=>{assert.equal(validateMapping(mapping).haarProductId,haarProductId);assert.throws(()=>validateMapping({...mapping,haarProductId:mapping.channelProductKey}));assert.throws(()=>validateMapping({...mapping,channelProductKey:haarProductId}));});
test('manual_mapping_cannot_claim_live_evidence',()=>{for(const extra of [{liveVerified:true},{confidence:1},{method:'exact'},{trusted:true}])assert.throws(()=>validateMapping({...mapping,...extra}));assert.equal(validateMapping(mapping).liveVerified,false);});
test('shared_ad_mapping_needs_weights',()=>{assert.throws(()=>normalizeAllocation(null,[haarProductId,other]));assert.throws(()=>normalizeAllocation({weights:[{haarProductId,weight:'1'},{haarProductId:other,weight:'1'}]},[haarProductId,other]));assert.equal(normalizeAllocation({weights:[{haarProductId,weight:'0.4'},{haarProductId:other,weight:'0.6'}]},[haarProductId,other]).verified,false);});
test('missing values stay null and unexpected buyer fields never survive safe row projection',()=>{for(const v of [null,undefined,'',' ','no',Infinity])assert.equal(money(v),null);assert.equal(money(0),'0');assert.deepEqual(safeRows([{sourceReference:'a'.repeat(64),buyerName:'SECRET',url:'https://secret',paidAmountKrw:null}]),[{sourceReference:'a'.repeat(64),paidAmountKrw:null}]);});
test('provider selector permits only exact pinned read-only operations',async()=>{for(const descriptor of Object.values(NAVER_EVIDENCE_READS)){assert.equal(descriptor.method,'GET');const op=loadCommerceManifest().operations.find(x=>x.operationId===descriptor.operationId);assert.equal(op.readOnly,true);assert.equal(op.path,descriptor.path);}const {provider,calls}=naver({});await assert.rejects(()=>provider.read('delete_v2_products_channel_products_by_channel_product_no',{}));assert.equal(calls.length,0);});
test('configured Naver product, orders, adjustments and settlements delegate safe server requests',async()=>{const {provider,calls}=naver({[NAVER_EVIDENCE_READS.product.operationId]:fixture('naver-product'),[NAVER_EVIDENCE_READS.orders.operationId]:fixture('naver-orders'),[NAVER_EVIDENCE_READS.settlements.operationId]:fixture('naver-settlements')});const state=await provider.collectProductState(scope);assert.equal(state.rows[0].stockQuantity,'5');const orders=await provider.collectOrderLines(scope);assert.equal(orders.rows.length,1);assert.equal(orders.rows[0].netRevenueKrw,'7000');const adjustments=await provider.collectAdjustments(scope);assert.equal(adjustments.rows.length,1);assert.equal(adjustments.rows[0].alreadyIncludedInNetRevenue,true);assert.equal(adjustments.rows[0].amountKrw,null);const settle=await provider.collectSettlements(scope);assert.equal(settle.rows[0].paySettleAmountKrw,'7000');assert.equal(settle.complete,false);assert.equal(JSON.stringify([state,orders,adjustments,settle]).includes('PRIVATE_BUYER'),false);assert.ok(calls.every(x=>Object.values(NAVER_EVIDENCE_READS).some(d=>d.operationId===x.id)));assert.equal(calls[0].input.pathParams.channelProductNo,'123');});
test('order_adjustment_identity_deduplicates',async()=>{const {provider}=naver({[NAVER_EVIDENCE_READS.orders.operationId]:fixture('naver-orders')});assert.equal((await provider.collectOrderLines(scope)).rows.length,1);assert.equal((await provider.collectAdjustments(scope)).rows.length,1);});
test('haar_own_mall_not_duplicated_as_cafe24_channel',async()=>{const calls=[];const provider=new Cafe24CommerceEvidenceProvider({client:{async get(path,options){calls.push({path,options});return {data:path.endsWith('/variants')?fixture('cafe24-variants'):fixture('cafe24-product')};}},shopNo:1,sourceIdentity:'b'.repeat(64),clock});const result=await provider.collectProductState({...scope,channelId:'haar_own_mall'});assert.equal(result.rows[0].saleState,'SALE');assert.ok(calls.every(x=>x.path.startsWith('/admin/products/123')));assert.equal((await provider.collectSettlements(scope)).complete,false);assert.equal((await provider.collectSettlements(scope)).missingReasons[0],'CAFE24_SETTLEMENT_CAPABILITY_UNVERIFIED');});
test('empty or malformed provider responses are never complete zero inventory',async()=>{const {provider}=naver({});for(const method of ['collectProductState','collectOrderLines','collectAdjustments','collectSettlements']){const result=await provider[method](scope);assert.equal(result.complete,false);assert.deepEqual(result.rows,[]);assert.ok(result.missingReasons.length);}});
test('descriptor drift cannot turn a product read into a write',async()=>{const {provider,calls}=naver({});const original=provider.gateway.get;provider.gateway.get=id=>({...original(id),method:'DELETE',readOnly:false,sideEffect:true});await assert.rejects(()=>provider.collectProductState(scope),{code:'SEARCHAD_COMMERCE_DESCRIPTOR_CHANGED'});assert.equal(calls.length,0);});
test('provider pagination requires explicit exhaustion, and conflicting duplicates remain partial',async()=>{const order=fixture('naver-orders');delete order.data.pagination;order.data.contents[1].content.productOrder.remainPaymentAmount=6000;const {provider}=naver({[NAVER_EVIDENCE_READS.orders.operationId]:order});const result=await provider.collectOrderLines(scope);assert.equal(result.complete,false);assert.ok(result.missingReasons.includes('ORDER_PAGINATION_UNVERIFIED'));assert.ok(result.missingReasons.includes('CONFLICTING_SOURCE_IDENTITY'));});
import { searchAdCompletionOpenApi } from '../src/http/openapi-searchad-completion.js';
test('product evidence role OpenAPI has exact bodies and no execution/authority inputs',()=>{for(const role of ['reader','operator','executor','admin']){const paths=searchAdCompletionOpenApi({role}).paths;assert.ok(paths['/api/v1/searchad/profitability/products/{haarProductId}']);assert.equal(Boolean(paths['/api/v1/searchad/product-evidence/collect']),role!=='reader');for(const route of ['product-mappings','product-costs','customer-channel-bindings'])assert.equal(Boolean(paths[`/api/v1/searchad/${route}`]),role==='admin');}const paths=searchAdCompletionOpenApi({role:'admin'}).paths;for(const route of ['product-mappings','product-costs','customer-channel-bindings','product-evidence/collect']){const schema=paths[`/api/v1/searchad/${route}`].post.requestBody.content['application/json'].schema;assert.equal(schema.additionalProperties,false);for(const bad of ['operationId','path','accountId','credential','trusted','liveVerified','autoEligible','confidence'])assert.equal(Object.hasOwn(schema.properties,bad),false);}});

test('T9-I2 producer money rejects fractional and unsafe numbers before stringification',async()=>{
  for(const [value,expected] of [[1.2,null],[Number.MAX_SAFE_INTEGER+1,null],[1200,'1200'],['1.2000','1.2000']]){
    assert.equal(money(value),expected);assert.equal(safeRows([{sourceReference:'a'.repeat(64),paidAmountKrw:value}])[0].paidAmountKrw,expected);
    const orders=fixture('naver-orders');for(const item of orders.data.contents)if(item.content.productOrder.productId==='123'){item.content.productOrder.initialPaymentAmount=value;item.content.productOrder.remainPaymentAmount=value;}
    const {provider}=naver({[NAVER_EVIDENCE_READS.orders.operationId]:orders});const result=await provider.collectOrderLines(scope);
    assert.equal(result.rows[0].netRevenueKrw,expected);assert.equal(result.complete,expected!==null);assert.equal(result.missingReasons.includes('ORDER_FIELDS_MISSING'),expected===null);
  }
});
