import test from 'node:test';
import assert from 'node:assert/strict';
import { recommend } from '../src/naver/searchad/profitability/recommendation-rules.js';
const now=Date.parse('2026-10-05T03:00:00Z');
function inputs(){return {customerId:'1001',haarProductId:'11111111-1111-4111-8111-111111111111',inputHash:'a'.repeat(64),asOf:new Date(now).toISOString(),quality:'actual',metrics:{contributionKrw:'49000',conversions:'3'},missingReasons:[],mappingVerified:true,allocationVerified:true,tools:{keywordIdeas:{status:'available',ideas:['silver']},bidEstimate:{status:'unavailable',reason:'ESTIMATE_READ_CAPABILITY_UNAVAILABLE'}},campaign:{entityId:'cmp-1',dailyBudget:'10000'},balanceVerified:false};}
test('same_inputs_same_recommendations',()=>assert.deepEqual(recommend(inputs(),{now}),recommend(inputs(),{now})));
test('two_conversions_cannot_recommend_increase',()=>{const i=inputs();i.metrics.conversions='2';const rows=recommend(i,{now});assert.ok(rows.find(r=>r.category==='budget').blockedReasons.includes('SPARSE_CONVERSIONS'));assert.equal(rows.some(r=>r.patch?.dailyBudget>10000),false);});
test('unsupported_negative_keyword_is_nonexecutable',()=>{const row=recommend(inputs(),{now}).find(r=>r.category==='negative');assert.equal(row.executable,false);assert.ok(row.blockedReasons.includes('NEGATIVE_MUTATION_MAPPING_UNSUPPORTED'));});
test('all decisions carry reasons, confidence, expiry and validator constraints without execution proof',()=>{for(const row of recommend(inputs(),{now})){assert.ok(row.reason);assert.ok(row.expiresAt);assert.ok(row.confidence);assert.equal(row.executable,false);assert.equal(row.outcomeVerified,false);assert.ok(row.activationConstraints.length);}});
for(const [name,change]of [['stale',i=>i.asOf='2026-10-01T00:00:00Z'],['partial',i=>i.quality='partial'],['mapping',i=>i.mappingVerified=false],['allocation',i=>i.allocationVerified=false]])test(`${name} cannot produce increases`,()=>{const i=inputs();change(i);assert.equal(recommend(i,{now}).some(r=>r.patch?.dailyBudget>10000),false);});
test('complete actual evidence can propose bounded budget change while retaining manual activation constraints',()=>{const i=inputs();i.tools.bidEstimate={status:'available',verified:true};i.balanceVerified=true;const r=recommend(i,{now}).find(r=>r.category==='budget');assert.deepEqual(r.patch,{dailyBudget:12000});assert.equal(r.executable,false);});
import { reportingFixture } from './helpers/searchad-completion-fixture.js';
import { SearchAdRecommendationToolAdapter, KEYWORD_READ } from '../src/naver/searchad/profitability/tool-adapter.js';
test('keyword tool uses pinned read and estimate never sends POST',async()=>{const f=reportingFixture({response:{keywordList:[{relKeyword:'silver'},{relKeyword:'silver'},{relKeyword:'gold'}]}});f.config.allowUnverifiedOperations=true;const tool=new SearchAdRecommendationToolAdapter({gateway:f.gateway,identityResolver:f.identityResolver});const r=await tool.keywordIdeas({customerId:'1001',hintKeywords:['ring']});assert.deepEqual(r.ideas,['gold','silver']);assert.equal(f.calls.length,1);assert.equal(f.calls[0].method,'GET');assert.equal(new URL(f.calls[0].url).pathname,'/keywordstool');assert.equal((await tool.bidEstimate({customerId:'1001'})).reason,'ESTIMATE_READ_CAPABILITY_UNAVAILABLE');assert.equal(f.calls.length,1);f.registry.get(KEYWORD_READ).sideEffect=true;assert.equal((await tool.keywordIdeas({customerId:'1001',hintKeywords:['ring']})).reason,'KEYWORD_READ_DESCRIPTOR_UNSUPPORTED');assert.equal(f.calls.length,1);});
test('default keyword capability gate and changed identity deny tool evidence',async()=>{const f=reportingFixture({response:{keywordList:[{relKeyword:'ring'}]},afterRequest(){f.rotate();}});const tool=new SearchAdRecommendationToolAdapter({gateway:f.gateway,identityResolver:f.identityResolver});f.config.allowReads=false;assert.equal((await tool.keywordIdeas({customerId:'1001',hintKeywords:['ring']})).status,'unavailable');assert.equal(f.calls.length,0);f.config.allowReads=true;f.config.allowUnverifiedOperations=true;await assert.rejects(()=>tool.keywordIdeas({customerId:'1001',hintKeywords:['ring']}),{code:'SEARCHAD_COMMERCE_IDENTITY_CHANGED'});});
import { searchAdCompletionOpenApi } from '../src/http/openapi-searchad-completion.js';
test('OpenAPI exposes scoped Reader reads and Operator generation without any execution endpoint',()=>{for(const role of ['reader','operator','executor','admin']){const doc=searchAdCompletionOpenApi({role});assert.ok(doc.paths['/api/v1/searchad/recommendations']?.get);assert.equal(Boolean(doc.paths['/api/v1/searchad/recommendations/generate']),role!=='reader');assert.equal(Object.keys(doc.paths).some(p=>p.includes('recommendations')&&p.endsWith('/execute')),false);}});
