import test from 'node:test';
import assert from 'node:assert/strict';
import { calculateProfitability, allocateSpend, summarizeOrders } from '../src/naver/searchad/profitability/calculator.js';
export function completeInputs(){return {customerId:'1001',haarProductId:'11111111-1111-4111-8111-111111111111',since:'2026-10-01',until:'2026-10-01',asOf:'2026-10-05T03:00:00.000Z',mappingVerified:true,allocationVerified:true,components:Object.fromEntries(Object.entries({paidRevenue:100000,netRevenue:100000,cogs:30000,fees:5000,shipping:3000,sellerDiscount:2000,returnProvision:1000,adCost:10000,adAttributedRevenue:200000}).map(([k,v])=>[k,{amountKrw:String(v),quality:'actual',reconciled:true,alreadyIncludedInNetRevenue:false,sourceHash:k}])),counts:{conversions:'3',clicks:'100'},missingReasons:[]};}
test('complete_actual_golden',()=>{const s=calculateProfitability(completeInputs());assert.equal(s.metrics.contributionKrw,'49000');assert.equal(s.metrics.netRevenueKrw,'100000');assert.equal(s.quality,'actual');assert.equal(s.metrics.grossMarginKrw,'70000');assert.equal(s.metrics.roas,'20');});
test('explicit estimated, partial and unknown quality',()=>{const i=completeInputs();i.components.cogs.quality='estimated';assert.equal(calculateProfitability(i).quality,'estimated');delete i.components.cogs;assert.equal(calculateProfitability(i).quality,'partial');assert.equal(calculateProfitability({}).quality,'unknown');});
test('missing_cogs_yields_null_contribution',()=>{const i=completeInputs();delete i.components.cogs;const s=calculateProfitability(i);assert.equal(s.metrics.contributionKrw,null);assert.ok(s.missingReasons.includes('COGS_MISSING'));});
test('zero_denominator_yields_null',()=>{const i=completeInputs();for(const k of ['netRevenue','adCost','adAttributedRevenue'])i.components[k].amountKrw='0';i.counts={conversions:'0',clicks:'0'};const s=calculateProfitability(i);for(const k of ['marginRate','roas','acos','cpaKrw','cvr','profitRoas','breakEvenRoas'])assert.equal(s.metrics[k],null,k);});
test('refund_not_subtracted_twice',()=>{const i=completeInputs();i.components.returnProvision={...i.components.returnProvision,amountKrw:null,alreadyIncludedInNetRevenue:true};const s=calculateProfitability(i);assert.equal(s.metrics.contributionKrw,'50000');assert.equal(s.componentProvenance.returnProvision.deductedKrw,'0');});
test('each deducted component declares whether it is already netted',()=>{for(const k of ['cogs','fees','shipping','sellerDiscount','returnProvision','adCost']){const i=completeInputs();i.components[k].alreadyIncludedInNetRevenue=true;assert.equal(calculateProfitability(i).metrics.contributionKrw,String(49000+Number(i.components[k].amountKrw)));delete i.components[k].alreadyIncludedInNetRevenue;assert.equal(calculateProfitability(i).metrics.contributionKrw,null,k);}});
test('exact high precision money and explicit half away ratio rounding',()=>{const i=completeInputs();i.components.netRevenue.amountKrw='99999999999999.9999';i.components.cogs.amountKrw='0.0001';const s=calculateProfitability(i);assert.equal(s.metrics.contributionKrw,'99999999978999.9998');assert.equal(s.basis.moneyScale,4);});
test('shared_spend_allocated_once',()=>{const rows=[{sourceKey:'generation-1:row-1',generation:'g1',amountKrw:'10000',weights:[{haarProductId:'a',weight:'0.6'},{haarProductId:'b',weight:'0.4'}],verified:true,allocationGeneration:'g1'}];assert.equal(allocateSpend([...rows,...rows],'a').allocatedKrw,'6000');assert.equal(allocateSpend(rows,'b').allocatedKrw,'4000');assert.equal(allocateSpend([{...rows[0],verified:false}],'a').allocatedKrw,null);assert.equal(allocateSpend([{...rows[0],allocationGeneration:'g2'}],'a').unallocatedKrw,'10000');});
test('ad_attribution_is_not_commerce_revenue',()=>{const s=calculateProfitability(completeInputs());assert.equal(s.metrics.adAttributedRevenueKrw,'200000');assert.equal(s.metrics.netRevenueKrw,'100000');assert.equal(s.metrics.contributionKrw,'49000');});
test('two channels and repeated rows preserve each order once and reject conflicts',()=>{const rows=[{sourceReference:'naver-order',paidAmountKrw:'70000',netRevenueKrw:'60000',remainingQuantity:'2'},{sourceReference:'cafe-order',paidAmountKrw:'40000',netRevenueKrw:'40000',remainingQuantity:'1'}];assert.deepEqual(summarizeOrders([...rows,...rows]),{paidRevenueKrw:'110000',netRevenueKrw:'100000',quantity:'3',conflict:false});assert.equal(summarizeOrders([...rows,{...rows[0],netRevenueKrw:'1'}]).netRevenueKrw,null);});
test('shared allocation rounding conserves one unit across all products',()=>{const rows=[{sourceKey:'tiny',generation:'g1',allocationGeneration:'g1',verified:true,amountKrw:'0.0001',weights:[{haarProductId:'a',weight:'0.5'},{haarProductId:'b',weight:'0.5'}]}];assert.equal(allocateSpend(rows,'a').allocatedKrw,'0.0001');assert.equal(allocateSpend(rows,'b').allocatedKrw,'0');});
test('missing spend stays null rather than zero unallocated money',()=>{assert.equal(allocateSpend([],'a').unallocatedKrw,null);assert.equal(allocateSpend([{sourceKey:'x',amountKrw:null}],'a').unallocatedKrw,null);});
test('raw decimal spelling is retained alongside normalized exact-money provenance',()=>{const i=completeInputs();i.components.cogs.amountKrw='1.2000';const s=calculateProfitability(i);assert.equal(s.componentProvenance.cogs.amountKrw,'1.2');assert.equal(s.componentProvenance.cogs.rawAmountKrw,'1.2000');});
test('unsafe numeric money cannot silently become an exact financial amount',()=>{const i=completeInputs();i.components.cogs.amountKrw=Number.MAX_SAFE_INTEGER+1;const s=calculateProfitability(i);assert.equal(s.metrics.cogsKrw,null);assert.equal(s.metrics.contributionKrw,null);});
