import {useState} from 'react';
import {amount} from './format.js';
function TargetRow({item,type,currency,busy,onPrepare}){
 const [budget,setBudget]=useState('');const budgetType=Number(item.daily_budget)>0?'daily':Number(item.lifetime_budget)>0?'lifetime':null;
 return <tr><th>{item.name||item.id}<small>{item.id}{item.campaign_id?' · 캠페인 '+item.campaign_id:''}{item.adset_id?' · 광고세트 '+item.adset_id:''}</small></th><td>{item.effective_status||item.status||'—'}</td><td>{budgetType?amount(item[budgetType+'_budget'],currency,true)+(budgetType==='daily'?' / 일':' / 전체'):'상위 설정 사용'}</td><td><div className="ads-row-actions"><button className="button button-secondary" disabled={busy} onClick={()=>onPrepare({actionType:'pause',targetType:type,targetId:item.id})}>중지 승인 요청</button><button className="button button-secondary" disabled={busy} onClick={()=>onPrepare({actionType:'resume',targetType:type,targetId:item.id})}>재개 승인 요청</button></div>{budgetType&&type!=='ad'?<form className="ads-budget-edit" onSubmit={e=>{e.preventDefault();onPrepare({actionType:'change_budget',targetType:type,targetId:item.id,budgetType,budgetAmount:budget});}}><input aria-label={`${item.name||item.id} 새 예산 (${currency})`} inputMode="decimal" required placeholder={`새 예산 (${currency})`} value={budget} onChange={e=>setBudget(e.target.value)}/><button className="button button-secondary" disabled={busy||!budget}>예산 승인 요청</button></form>:null}</td></tr>;
}
export function AdsCampaigns({data,onRefresh,onPrepare,busy}){
 return <section className="panel"><div className="ads-heading"><div><span className="eyebrow">LIVE OBJECTS</span><h2>캠페인 · 광고세트 · 광고</h2><p>상태·예산 변경은 승인 요청만 준비합니다. 실행은 승인 탭에서 별도로 합니다.</p></div><button className="button button-primary" disabled={busy} onClick={onRefresh}>Meta 광고 목록 조회</button></div>
  {data?[['campaigns','campaign','캠페인'],['adsets','adset','광고세트'],['ads','ad','광고']].map(([key,type,title])=><section key={key} className="ads-hierarchy"><h3>{title} · {data[key]?.length||0}</h3>{data[key]?.length?<div className="ads-table-scroll"><table className="ads-table"><thead><tr><th>이름 / 연결 ID</th><th>상태</th><th>예산</th><th>승인 요청</th></tr></thead><tbody>{data[key].map(item=><TargetRow key={item.id} {...{item,type,busy,onPrepare}} currency={data.account.currency}/>)}</tbody></table></div>:<p>반환된 {title}이 없습니다.</p>}</section>):<p>조회 버튼을 눌러 현재 광고 계정의 목록을 불러오세요.</p>}
 </section>;
}
